# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' FeatureConfig Class
#'
#' @field maxVal 
#' @field minVal 
#' @field weight 
#' @field label 
#' @field submitRule 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FeatureConfig <- R6::R6Class("FeatureConfig", public = list(maxVal = NULL, minVal = NULL,
    weight = NULL, label = NULL, submitRule = NULL, initialize = function(maxVal,
        minVal, weight, label, submitRule) {
        if (!missing(maxVal)) {
            stopifnot(is.numeric(maxVal), length(maxVal) == 1)
            self$maxVal <- maxVal
        }
        if (!missing(minVal)) {
            stopifnot(is.numeric(minVal), length(minVal) == 1)
            self$minVal <- minVal
        }
        if (!missing(weight)) {
            stopifnot(is.numeric(weight), length(weight) == 1)
            self$weight <- weight
        }
        if (!missing(label)) {
            stopifnot(is.character(label), length(label) == 1)
            self$label <- label
        }
        if (!missing(submitRule)) {
            stopifnot(is.character(submitRule), length(submitRule) == 1)
            self$submitRule <- submitRule
        }
    }, toJSON = function() {
        FeatureConfigObject <- list()
        if (!is.null(self$maxVal)) {
            FeatureConfigObject[["maxVal"]] <- self$maxVal
        }
        if (!is.null(self$minVal)) {
            FeatureConfigObject[["minVal"]] <- self$minVal
        }
        if (!is.null(self$weight)) {
            FeatureConfigObject[["weight"]] <- self$weight
        }
        if (!is.null(self$label)) {
            FeatureConfigObject[["label"]] <- self$label
        }
        if (!is.null(self$submitRule)) {
            FeatureConfigObject[["submitRule"]] <- self$submitRule
        }

        FeatureConfigObject
    }, fromJSON = function(FeatureConfigJson) {
        FeatureConfigObject <- jsonlite::fromJSON(FeatureConfigJson)
        if (!is.null(FeatureConfigObject$maxVal)) {
            self$maxVal <- FeatureConfigObject$maxVal
        }
        if (!is.null(FeatureConfigObject$minVal)) {
            self$minVal <- FeatureConfigObject$minVal
        }
        if (!is.null(FeatureConfigObject$weight)) {
            self$weight <- FeatureConfigObject$weight
        }
        if (!is.null(FeatureConfigObject$label)) {
            self$label <- FeatureConfigObject$label
        }
        if (!is.null(FeatureConfigObject$submitRule)) {
            self$submitRule <- FeatureConfigObject$submitRule
        }
    }, toJSONString = function() {
        sprintf("{
           \"maxVal\": %d,
           \"minVal\": %d,
           \"weight\": %d,
           \"label\": %s,
           \"submitRule\": %s
        }",
            self$maxVal, self$minVal, self$weight, self$label, self$submitRule)
    }, fromJSONString = function(FeatureConfigJson) {
        FeatureConfigObject <- jsonlite::fromJSON(FeatureConfigJson)
        self$maxVal <- FeatureConfigObject$maxVal
        self$minVal <- FeatureConfigObject$minVal
        self$weight <- FeatureConfigObject$weight
        self$label <- FeatureConfigObject$label
        self$submitRule <- FeatureConfigObject$submitRule
    }))
