# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Float32Array Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Float32Array <- R6::R6Class("Float32Array", public = list(initialize = function() {
}, toJSON = function() {
    Float32ArrayObject <- list()

    Float32ArrayObject
}, fromJSON = function(Float32ArrayJson) {
    Float32ArrayObject <- jsonlite::fromJSON(Float32ArrayJson)
}, toJSONString = function() {
    sprintf("{
        }", )
}, fromJSONString = function(Float32ArrayJson) {
    Float32ArrayObject <- jsonlite::fromJSON(Float32ArrayJson)
}))
