# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' FusionConfig Class
#'
#' @field label 
#' @field submitRule 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FusionConfig <- R6::R6Class("FusionConfig", public = list(label = NULL, submitRule = NULL,
    initialize = function(label, submitRule) {
        if (!missing(label)) {
            stopifnot(is.character(label), length(label) == 1)
            self$label <- label
        }
        if (!missing(submitRule)) {
            stopifnot(is.character(submitRule), length(submitRule) == 1)
            self$submitRule <- submitRule
        }
    }, toJSON = function() {
        FusionConfigObject <- list()
        if (!is.null(self$label)) {
            FusionConfigObject[["label"]] <- self$label
        }
        if (!is.null(self$submitRule)) {
            FusionConfigObject[["submitRule"]] <- self$submitRule
        }

        FusionConfigObject
    }, fromJSON = function(FusionConfigJson) {
        FusionConfigObject <- jsonlite::fromJSON(FusionConfigJson)
        if (!is.null(FusionConfigObject$label)) {
            self$label <- FusionConfigObject$label
        }
        if (!is.null(FusionConfigObject$submitRule)) {
            self$submitRule <- FusionConfigObject$submitRule
        }
    }, toJSONString = function() {
        sprintf("{
           \"label\": %s,
           \"submitRule\": %s
        }",
            self$label, self$submitRule)
    }, fromJSONString = function(FusionConfigJson) {
        FusionConfigObject <- jsonlite::fromJSON(FusionConfigJson)
        self$label <- FusionConfigObject$label
        self$submitRule <- FusionConfigObject$submitRule
    }))
