# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GetConfigResponse Class
#'
#' @field anomalyHistoryWindow 
#' @field learningRateNumerator 
#' @field learningRateDenominator 
#' @field learningMaxClusters 
#' @field learningMaxSamples 
#' @field featureCount 
#' @field streamingWindowSize 
#' @field features 
#' @field percentVariation 
#' @field samplesToBuffer 
#' @field percentVariationOverride 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GetConfigResponse <- R6::R6Class(
  'GetConfigResponse',
  public = list(
    `anomalyHistoryWindow` = NULL,
    `learningRateNumerator` = NULL,
    `learningRateDenominator` = NULL,
    `learningMaxClusters` = NULL,
    `learningMaxSamples` = NULL,
    `featureCount` = NULL,
    `streamingWindowSize` = NULL,
    `features` = NULL,
    `percentVariation` = NULL,
    `samplesToBuffer` = NULL,
    `percentVariationOverride` = NULL,
    initialize = function(`anomalyHistoryWindow`, `learningRateNumerator`, `learningRateDenominator`, `learningMaxClusters`, `learningMaxSamples`, `featureCount`, `streamingWindowSize`, `features`, `percentVariation`, `samplesToBuffer`, `percentVariationOverride`){
      if (!missing(`anomalyHistoryWindow`)) {
        stopifnot(is.numeric(`anomalyHistoryWindow`), length(`anomalyHistoryWindow`) == 1)
        stopifnot(R6::is.R6(`anomalyHistoryWindow`))
        self$`anomalyHistoryWindow` <- `anomalyHistoryWindow`
      }
      if (!missing(`learningRateNumerator`)) {
        stopifnot(is.numeric(`learningRateNumerator`), length(`learningRateNumerator`) == 1)
        stopifnot(R6::is.R6(`learningRateNumerator`))
        self$`learningRateNumerator` <- `learningRateNumerator`
      }
      if (!missing(`learningRateDenominator`)) {
        stopifnot(is.numeric(`learningRateDenominator`), length(`learningRateDenominator`) == 1)
        stopifnot(R6::is.R6(`learningRateDenominator`))
        self$`learningRateDenominator` <- `learningRateDenominator`
      }
      if (!missing(`learningMaxClusters`)) {
        stopifnot(is.numeric(`learningMaxClusters`), length(`learningMaxClusters`) == 1)
        stopifnot(R6::is.R6(`learningMaxClusters`))
        self$`learningMaxClusters` <- `learningMaxClusters`
      }
      if (!missing(`learningMaxSamples`)) {
        stopifnot(is.numeric(`learningMaxSamples`), length(`learningMaxSamples`) == 1)
        stopifnot(R6::is.R6(`learningMaxSamples`))
        self$`learningMaxSamples` <- `learningMaxSamples`
      }
      if (!missing(`featureCount`)) {
        stopifnot(is.numeric(`featureCount`), length(`featureCount`) == 1)
        self$`featureCount` <- `featureCount`
      }
      if (!missing(`streamingWindowSize`)) {
        stopifnot(is.numeric(`streamingWindowSize`), length(`streamingWindowSize`) == 1)
        self$`streamingWindowSize` <- `streamingWindowSize`
      }
      if (!missing(`features`)) {
        stopifnot(is.list(`features`), length(`features`) != 0)
        lapply(`features`, function(x) stopifnot(R6::is.R6(x)))
        self$`features` <- `features`
      }
      if (!missing(`percentVariation`)) {
        stopifnot(is.numeric(`percentVariation`), length(`percentVariation`) == 1)
        self$`percentVariation` <- `percentVariation`
      }
      if (!missing(`samplesToBuffer`)) {
        stopifnot(is.numeric(`samplesToBuffer`), length(`samplesToBuffer`) == 1)
        stopifnot(R6::is.R6(`samplesToBuffer`))
        self$`samplesToBuffer` <- `samplesToBuffer`
      }
      if (!missing(`percentVariationOverride`)) {
        stopifnot(is.numeric(`percentVariationOverride`), length(`percentVariationOverride`) == 1)
        self$`percentVariationOverride` <- `percentVariationOverride`
      }
    },
    toJSON = function() {
      GetConfigResponseObject <- list()
      if (!is.null(self$`anomalyHistoryWindow`)) {
        GetConfigResponseObject[['anomalyHistoryWindow']] <- self$`anomalyHistoryWindow`
      }
      if (!is.null(self$`learningRateNumerator`)) {
        GetConfigResponseObject[['learningRateNumerator']] <- self$`learningRateNumerator`
      }
      if (!is.null(self$`learningRateDenominator`)) {
        GetConfigResponseObject[['learningRateDenominator']] <- self$`learningRateDenominator`
      }
      if (!is.null(self$`learningMaxClusters`)) {
        GetConfigResponseObject[['learningMaxClusters']] <- self$`learningMaxClusters`
      }
      if (!is.null(self$`learningMaxSamples`)) {
        GetConfigResponseObject[['learningMaxSamples']] <- self$`learningMaxSamples`
      }
      if (!is.null(self$`featureCount`)) {
        GetConfigResponseObject[['featureCount']] <- self$`featureCount`
      }
      if (!is.null(self$`streamingWindowSize`)) {
        GetConfigResponseObject[['streamingWindowSize']] <- self$`streamingWindowSize`
      }
      if (!is.null(self$`features`)) {
        GetConfigResponseObject[['features']] <- lapply(self$`features`, function(x) x$toJSON())
      }
      if (!is.null(self$`percentVariation`)) {
        GetConfigResponseObject[['percentVariation']] <- self$`percentVariation`
      }
      if (!is.null(self$`samplesToBuffer`)) {
        GetConfigResponseObject[['samplesToBuffer']] <- self$`samplesToBuffer`
      }
      if (!is.null(self$`percentVariationOverride`)) {
        GetConfigResponseObject[['percentVariationOverride']] <- self$`percentVariationOverride`
      }

      GetConfigResponseObject
    },
    fromJSON = function(GetConfigResponseJson) {
      GetConfigResponseObject <- jsonlite::fromJSON(GetConfigResponseJson, simplifyVector = FALSE)
      if (!is.null(GetConfigResponseObject$`anomalyHistoryWindow`)) {
        self$`anomalyHistoryWindow` <- GetConfigResponseObject$anomalyHistoryWindow
      }
      if (!is.null(GetConfigResponseObject$`learningRateNumerator`)) {
        self$`learningRateNumerator` <- GetConfigResponseObject$learningRateNumerator
      }
      if (!is.null(GetConfigResponseObject$`learningRateDenominator`)) {
        self$`learningRateDenominator` <- GetConfigResponseObject$learningRateDenominator
      }
      if (!is.null(GetConfigResponseObject$`learningMaxClusters`)) {
        self$`learningMaxClusters` <- GetConfigResponseObject$learningMaxClusters
      }
      if (!is.null(GetConfigResponseObject$`learningMaxSamples`)) {
        self$`learningMaxSamples` <- GetConfigResponseObject$learningMaxSamples
      }
      if (!is.null(GetConfigResponseObject$`featureCount`)) {
        self$`featureCount` <- GetConfigResponseObject$`featureCount`
      }
      if (!is.null(GetConfigResponseObject$`streamingWindowSize`)) {
        self$`streamingWindowSize` <- GetConfigResponseObject$`streamingWindowSize`
      }
      if (!is.null(GetConfigResponseObject$`features`)) {
        self$`features` <- lapply(GetConfigResponseObject$`features`, function(x) {
          featuresObject <- FeatureConfig$new()
          featuresObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          featuresObject
        })
      }
      if (!is.null(GetConfigResponseObject$`percentVariation`)) {
        self$`percentVariation` <- GetConfigResponseObject$`percentVariation`
      }
      if (!is.null(GetConfigResponseObject$`samplesToBuffer`)) {
        self$`samplesToBuffer` <- GetConfigResponseObject$samplesToBuffer
      }
      if (!is.null(GetConfigResponseObject$`percentVariationOverride`)) {
        self$`percentVariationOverride` <- GetConfigResponseObject$`percentVariationOverride`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "anomalyHistoryWindow": %s,
           "learningRateNumerator": %s,
           "learningRateDenominator": %s,
           "learningMaxClusters": %s,
           "learningMaxSamples": %s,
           "featureCount": %d,
           "streamingWindowSize": %d,
           "features": [%s],
           "percentVariation": %d,
           "samplesToBuffer": %s,
           "percentVariationOverride": %d
        }',
        self$`anomalyHistoryWindow`,
        self$`learningRateNumerator`,
        self$`learningRateDenominator`,
        self$`learningMaxClusters`,
        self$`learningMaxSamples`,
        self$`featureCount`,
        self$`streamingWindowSize`,
        lapply(self$`features`, function(x) paste(x$toJSON(), sep=",")),
        self$`percentVariation`,
        self$`samplesToBuffer`,
        self$`percentVariationOverride`
      )
    },
    fromJSONString = function(GetConfigResponseJson) {
      GetConfigResponseObject <- jsonlite::fromJSON(GetConfigResponseJson, simplifyVector = FALSE)
      self$`anomalyHistoryWindow` <- GetConfigResponseObject$anomalyHistoryWindow
      self$`learningRateNumerator` <- GetConfigResponseObject$learningRateNumerator
      self$`learningRateDenominator` <- GetConfigResponseObject$learningRateDenominator
      self$`learningMaxClusters` <- GetConfigResponseObject$learningMaxClusters
      self$`learningMaxSamples` <- GetConfigResponseObject$learningMaxSamples
      self$`featureCount` <- GetConfigResponseObject$`featureCount`
      self$`streamingWindowSize` <- GetConfigResponseObject$`streamingWindowSize`
      self$`features` <- lapply(GetConfigResponseObject$`features`, function(x) FeatureConfig$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`percentVariation` <- GetConfigResponseObject$`percentVariation`
      self$`samplesToBuffer` <- GetConfigResponseObject$samplesToBuffer
      self$`percentVariationOverride` <- GetConfigResponseObject$`percentVariationOverride`
    }
  )
)

