# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GetRootCauseResponse Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GetRootCauseResponse <- R6::R6Class(
  'GetRootCauseResponse',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      GetRootCauseResponseObject <- list()

      GetRootCauseResponseObject
    },
    fromJSON = function(GetRootCauseResponseJson) {
      GetRootCauseResponseObject <- jsonlite::fromJSON(GetRootCauseResponseJson, simplifyVector = FALSE)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(GetRootCauseResponseJson) {
      GetRootCauseResponseObject <- jsonlite::fromJSON(GetRootCauseResponseJson)
    }
  )
)
