# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GetStatusResponse Class
#'
#' @field pca 
#' @field clusterGrowth 
#' @field clusterSizes 
#' @field anomalyIndexes 
#' @field frequencyIndexes 
#' @field distanceIndexes 
#' @field totalInferences 
#' @field numClusters 
#' @field anomalyThreshold 
#' @field state 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GetStatusResponse <- R6::R6Class(
  'GetStatusResponse',
  public = list(
    `pca` = NULL,
    `clusterGrowth` = NULL,
    `clusterSizes` = NULL,
    `anomalyIndexes` = NULL,
    `frequencyIndexes` = NULL,
    `distanceIndexes` = NULL,
    `totalInferences` = NULL,
    `numClusters` = NULL,
    `anomalyThreshold` = NULL,
    `state` = NULL,
    initialize = function(`pca`, `clusterGrowth`, `clusterSizes`, `anomalyIndexes`, `frequencyIndexes`, `distanceIndexes`, `totalInferences`, `numClusters`, `anomalyThreshold`, `state`){
      if (!missing(`pca`)) {
        stopifnot(R6::is.R6(`pca`))
        self$`pca` <- `pca`
      }
      if (!missing(`clusterGrowth`)) {
        stopifnot(R6::is.R6(`clusterGrowth`))
        self$`clusterGrowth` <- `clusterGrowth`
      }
      if (!missing(`clusterSizes`)) {
        stopifnot(R6::is.R6(`clusterSizes`))
        self$`clusterSizes` <- `clusterSizes`
      }
      if (!missing(`anomalyIndexes`)) {
        stopifnot(R6::is.R6(`anomalyIndexes`))
        self$`anomalyIndexes` <- `anomalyIndexes`
      }
      if (!missing(`frequencyIndexes`)) {
        stopifnot(R6::is.R6(`frequencyIndexes`))
        self$`frequencyIndexes` <- `frequencyIndexes`
      }
      if (!missing(`distanceIndexes`)) {
        stopifnot(R6::is.R6(`distanceIndexes`))
        self$`distanceIndexes` <- `distanceIndexes`
      }
      if (!missing(`totalInferences`)) {
        stopifnot(is.numeric(`totalInferences`), length(`totalInferences`) == 1)
        stopifnot(R6::is.R6(`totalInferences`))
        self$`totalInferences` <- `totalInferences`
      }
      if (!missing(`numClusters`)) {
        stopifnot(is.numeric(`numClusters`), length(`numClusters`) == 1)
        stopifnot(R6::is.R6(`numClusters`))
        self$`numClusters` <- `numClusters`
      }
      if (!missing(`anomalyThreshold`)) {
        stopifnot(is.numeric(`anomalyThreshold`), length(`anomalyThreshold`) == 1)
        self$`anomalyThreshold` <- `anomalyThreshold`
      }
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
    },
    toJSON = function() {
      GetStatusResponseObject <- list()
      if (!is.null(self$`pca`)) {
        GetStatusResponseObject[['pca']] <- self$`pca`$toJSON()
      }
      if (!is.null(self$`clusterGrowth`)) {
        GetStatusResponseObject[['clusterGrowth']] <- self$`clusterGrowth`
      }
      if (!is.null(self$`clusterSizes`)) {
        GetStatusResponseObject[['clusterSizes']] <- self$`clusterSizes`
      }
      if (!is.null(self$`anomalyIndexes`)) {
        GetStatusResponseObject[['anomalyIndexes']] <- self$`anomalyIndexes`
      }
      if (!is.null(self$`frequencyIndexes`)) {
        GetStatusResponseObject[['frequencyIndexes']] <- self$`frequencyIndexes`
      }
      if (!is.null(self$`distanceIndexes`)) {
        GetStatusResponseObject[['distanceIndexes']] <- self$`distanceIndexes`
      }
      if (!is.null(self$`totalInferences`)) {
        GetStatusResponseObject[['totalInferences']] <- self$`totalInferences`
      }
      if (!is.null(self$`numClusters`)) {
        GetStatusResponseObject[['numClusters']] <- self$`numClusters`
      }
      if (!is.null(self$`anomalyThreshold`)) {
        GetStatusResponseObject[['anomalyThreshold']] <- self$`anomalyThreshold`
      }
      if (!is.null(self$`state`)) {
        GetStatusResponseObject[['state']] <- self$`state`
      }

      GetStatusResponseObject
    },
    fromJSON = function(GetStatusResponseJson) {
      GetStatusResponseObject <- jsonlite::fromJSON(GetStatusResponseJson, simplifyVector = FALSE)
      if (!is.null(GetStatusResponseObject$`pca`)) {
        pcaObject <- PCA$new()
        pcaObject$fromJSON(jsonlite::toJSON(GetStatusResponseObject$pca, auto_unbox = TRUE))
        self$`pca` <- pcaObject
      }
      if (!is.null(GetStatusResponseObject$`clusterGrowth`)) {
        self$`clusterGrowth` <- GetStatusResponseObject$clusterGrowth
      }
      if (!is.null(GetStatusResponseObject$`clusterSizes`)) {
        self$`clusterSizes` <- GetStatusResponseObject$clusterSizes
      }
      if (!is.null(GetStatusResponseObject$`anomalyIndexes`)) {
        self$`anomalyIndexes` <- GetStatusResponseObject$anomalyIndexes
      }
      if (!is.null(GetStatusResponseObject$`frequencyIndexes`)) {
        self$`frequencyIndexes` <- GetStatusResponseObject$frequencyIndexes
      }
      if (!is.null(GetStatusResponseObject$`distanceIndexes`)) {
        self$`distanceIndexes` <- GetStatusResponseObject$distanceIndexes
      }
      if (!is.null(GetStatusResponseObject$`totalInferences`)) {
        self$`totalInferences` <- GetStatusResponseObject$totalInferences
      }
      if (!is.null(GetStatusResponseObject$`numClusters`)) {
        self$`numClusters` <- GetStatusResponseObject$numClusters
      }
      if (!is.null(GetStatusResponseObject$`anomalyThreshold`)) {
        self$`anomalyThreshold` <- GetStatusResponseObject$`anomalyThreshold`
      }
      if (!is.null(GetStatusResponseObject$`state`)) {
        self$`state` <- GetStatusResponseObject$`state`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "pca": %s,
           "clusterGrowth": %s,
           "clusterSizes": %s,
           "anomalyIndexes": %s,
           "frequencyIndexes": %s,
           "distanceIndexes": %s,
           "totalInferences": %s,
           "numClusters": %s,
           "anomalyThreshold": %d,
           "state": %s
        }',
        self$`pca`$toJSON(),
        self$`clusterGrowth`,
        self$`clusterSizes`,
        self$`anomalyIndexes`,
        self$`frequencyIndexes`,
        self$`distanceIndexes`,
        self$`totalInferences`,
        self$`numClusters`,
        self$`anomalyThreshold`,
        self$`state`
      )
    },
    fromJSONString = function(GetStatusResponseJson) {
      GetStatusResponseObject <- jsonlite::fromJSON(GetStatusResponseJson, simplifyVector = FALSE)
      PCAObject <- PCA$new()
      self$`pca` <- PCAObject$fromJSON(jsonlite::toJSON(GetStatusResponseObject$pca, auto_unbox = TRUE))
      self$`clusterGrowth` <- GetStatusResponseObject$clusterGrowth
      self$`clusterSizes` <- GetStatusResponseObject$clusterSizes
      self$`anomalyIndexes` <- GetStatusResponseObject$anomalyIndexes
      self$`frequencyIndexes` <- GetStatusResponseObject$frequencyIndexes
      self$`distanceIndexes` <- GetStatusResponseObject$distanceIndexes
      self$`totalInferences` <- GetStatusResponseObject$totalInferences
      self$`numClusters` <- GetStatusResponseObject$numClusters
      self$`anomalyThreshold` <- GetStatusResponseObject$`anomalyThreshold`
      self$`state` <- GetStatusResponseObject$`state`
    }
  )
)

