# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GetSensorResponse Class
#'
#' @field label 
#' @field sensorId 
#' @field usageInfo 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GetSensorResponse <- R6::R6Class(
  'GetSensorResponse',
  public = list(
    `label` = NULL,
    `sensorId` = NULL,
    `usageInfo` = NULL,
    initialize = function(`label`, `sensorId`, `usageInfo`){
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`sensorId`)) {
        stopifnot(is.character(`sensorId`), length(`sensorId`) == 1)
        self$`sensorId` <- `sensorId`
      }
      if (!missing(`usageInfo`)) {
        stopifnot(R6::is.R6(`usageInfo`))
        self$`usageInfo` <- `usageInfo`
      }
    },
    toJSON = function() {
      GetSensorResponseObject <- list()
      if (!is.null(self$`label`)) {
        GetSensorResponseObject[['label']] <- self$`label`
      }
      if (!is.null(self$`sensorId`)) {
        GetSensorResponseObject[['sensorId']] <- self$`sensorId`
      }
      if (!is.null(self$`usageInfo`)) {
        GetSensorResponseObject[['usageInfo']] <- self$`usageInfo`$toJSON()
      }

      GetSensorResponseObject
    },
    fromJSON = function(GetSensorResponseJson) {
      GetSensorResponseObject <- jsonlite::fromJSON(GetSensorResponseJson, simplifyVector = FALSE)
      if (!is.null(GetSensorResponseObject$`label`)) {
        self$`label` <- GetSensorResponseObject$`label`
      }
      if (!is.null(GetSensorResponseObject$`sensorId`)) {
        self$`sensorId` <- GetSensorResponseObject$`sensorId`
      }
      if (!is.null(GetSensorResponseObject$`usageInfo`)) {
        usageInfoObject <- SensorUsageInfo$new()
        usageInfoObject$fromJSON(jsonlite::toJSON(GetSensorResponseObject$usageInfo, auto_unbox = TRUE))
        self$`usageInfo` <- usageInfoObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "label": %s,
           "sensorId": %s,
           "usageInfo": %s
        }',
        self$`label`,
        self$`sensorId`,
        self$`usageInfo`$toJSON()
      )
    },
    fromJSONString = function(GetSensorResponseJson) {
      GetSensorResponseObject <- jsonlite::fromJSON(GetSensorResponseJson, simplifyVector = FALSE)
      self$`label` <- GetSensorResponseObject$`label`
      self$`sensorId` <- GetSensorResponseObject$`sensorId`
      SensorUsageInfoObject <- SensorUsageInfo$new()
      self$`usageInfo` <- SensorUsageInfoObject$fromJSON(jsonlite::toJSON(GetSensorResponseObject$usageInfo, auto_unbox = TRUE))
    }
  )
)

