# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GetSensorsResponse Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GetSensorsResponse <- R6::R6Class(
  'GetSensorsResponse',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      GetSensorsResponseObject <- list()

      GetSensorsResponseObject
    },
    fromJSON = function(GetSensorsResponseJson) {
      GetSensorsResponseObject <- jsonlite::fromJSON(GetSensorsResponseJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(GetSensorsResponseJson) {
      GetSensorsResponseObject <- jsonlite::fromJSON(GetSensorsResponseJson)
    }
  )
)
