# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MagicNumber Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MagicNumber <- R6::R6Class(
  'MagicNumber',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      MagicNumberObject <- list()

      MagicNumberObject
    },
    fromJSON = function(MagicNumberJson) {
      MagicNumberObject <- jsonlite::fromJSON(MagicNumberJson, simplifyVector = FALSE)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(MagicNumberJson) {
      MagicNumberObject <- jsonlite::fromJSON(MagicNumberJson, simplifyVector = FALSE)
    }
  )
)

