# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MAmberStatus Class
#'
#' @field VersionNumber 
#' @field m_Status 
#' @field m_Message 
#' @field m_Progress 
#' @field m_CurrentClusterCount 
#' @field m_RetryCount 
#' @field m_StreamingWindowSize 
#' @field m_TotalInferences 
#' @field m_TotalSamplesWritten 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MAmberStatus <- R6::R6Class("MAmberStatus", public = list(VersionNumber = NULL, m_Status = NULL,
    m_Message = NULL, m_Progress = NULL, m_CurrentClusterCount = NULL, m_RetryCount = NULL,
    m_StreamingWindowSize = NULL, m_TotalInferences = NULL, m_TotalSamplesWritten = NULL,
    initialize = function(VersionNumber, m_Status, m_Message, m_Progress, m_CurrentClusterCount,
        m_RetryCount, m_StreamingWindowSize, m_TotalInferences, m_TotalSamplesWritten) {
        if (!missing(VersionNumber)) {
            stopifnot(R6::is.R6(VersionNumber))
            self$VersionNumber <- VersionNumber
        }
        if (!missing(m_Status)) {
            stopifnot(is.character(m_Status), length(m_Status) == 1)
            self$m_Status <- m_Status
        }
        if (!missing(m_Message)) {
            stopifnot(is.character(m_Message), length(m_Message) == 1)
            self$m_Message <- m_Message
        }
        if (!missing(m_Progress)) {
            stopifnot(is.numeric(m_Progress), length(m_Progress) == 1)
            self$m_Progress <- m_Progress
        }
        if (!missing(m_CurrentClusterCount)) {
            stopifnot(is.numeric(m_CurrentClusterCount), length(m_CurrentClusterCount) ==
                1)
            self$m_CurrentClusterCount <- m_CurrentClusterCount
        }
        if (!missing(m_RetryCount)) {
            stopifnot(is.numeric(m_RetryCount), length(m_RetryCount) == 1)
            self$m_RetryCount <- m_RetryCount
        }
        if (!missing(m_StreamingWindowSize)) {
            stopifnot(is.numeric(m_StreamingWindowSize), length(m_StreamingWindowSize) ==
                1)
            self$m_StreamingWindowSize <- m_StreamingWindowSize
        }
        if (!missing(m_TotalInferences)) {
            stopifnot(is.numeric(m_TotalInferences), length(m_TotalInferences) ==
                1)
            self$m_TotalInferences <- m_TotalInferences
        }
        if (!missing(m_TotalSamplesWritten)) {
            stopifnot(is.numeric(m_TotalSamplesWritten), length(m_TotalSamplesWritten) ==
                1)
            self$m_TotalSamplesWritten <- m_TotalSamplesWritten
        }
    }, toJSON = function() {
        MAmberStatusObject <- list()
        if (!is.null(self$VersionNumber)) {
            MAmberStatusObject[["VersionNumber"]] <- self$VersionNumber$toJSON()
        }
        if (!is.null(self$m_Status)) {
            MAmberStatusObject[["m_Status"]] <- self$m_Status
        }
        if (!is.null(self$m_Message)) {
            MAmberStatusObject[["m_Message"]] <- self$m_Message
        }
        if (!is.null(self$m_Progress)) {
            MAmberStatusObject[["m_Progress"]] <- self$m_Progress
        }
        if (!is.null(self$m_CurrentClusterCount)) {
            MAmberStatusObject[["m_CurrentClusterCount"]] <- self$m_CurrentClusterCount
        }
        if (!is.null(self$m_RetryCount)) {
            MAmberStatusObject[["m_RetryCount"]] <- self$m_RetryCount
        }
        if (!is.null(self$m_StreamingWindowSize)) {
            MAmberStatusObject[["m_StreamingWindowSize"]] <- self$m_StreamingWindowSize
        }
        if (!is.null(self$m_TotalInferences)) {
            MAmberStatusObject[["m_TotalInferences"]] <- self$m_TotalInferences
        }
        if (!is.null(self$m_TotalSamplesWritten)) {
            MAmberStatusObject[["m_TotalSamplesWritten"]] <- self$m_TotalSamplesWritten
        }

        MAmberStatusObject
    }, fromJSON = function(MAmberStatusJson) {
        MAmberStatusObject <- jsonlite::fromJSON(MAmberStatusJson)
        if (!is.null(MAmberStatusObject$VersionNumber)) {
            VersionNumberObject <- VersionNumber$new()
            VersionNumberObject$fromJSON(jsonlite::toJSON(MAmberStatusObject$VersionNumber,
                auto_unbox = TRUE))
            self$VersionNumber <- VersionNumberObject
        }
        if (!is.null(MAmberStatusObject$m_Status)) {
            self$m_Status <- MAmberStatusObject$m_Status
        }
        if (!is.null(MAmberStatusObject$m_Message)) {
            self$m_Message <- MAmberStatusObject$m_Message
        }
        if (!is.null(MAmberStatusObject$m_Progress)) {
            self$m_Progress <- MAmberStatusObject$m_Progress
        }
        if (!is.null(MAmberStatusObject$m_CurrentClusterCount)) {
            self$m_CurrentClusterCount <- MAmberStatusObject$m_CurrentClusterCount
        }
        if (!is.null(MAmberStatusObject$m_RetryCount)) {
            self$m_RetryCount <- MAmberStatusObject$m_RetryCount
        }
        if (!is.null(MAmberStatusObject$m_StreamingWindowSize)) {
            self$m_StreamingWindowSize <- MAmberStatusObject$m_StreamingWindowSize
        }
        if (!is.null(MAmberStatusObject$m_TotalInferences)) {
            self$m_TotalInferences <- MAmberStatusObject$m_TotalInferences
        }
        if (!is.null(MAmberStatusObject$m_TotalSamplesWritten)) {
            self$m_TotalSamplesWritten <- MAmberStatusObject$m_TotalSamplesWritten
        }
    }, toJSONString = function() {
        sprintf("{
           \"VersionNumber\": %s,
           \"m_Status\": %s,
           \"m_Message\": %s,
           \"m_Progress\": %d,
           \"m_CurrentClusterCount\": %d,
           \"m_RetryCount\": %d,
           \"m_StreamingWindowSize\": %d,
           \"m_TotalInferences\": %d,
           \"m_TotalSamplesWritten\": %d
        }",
            self$VersionNumber$toJSON(), self$m_Status, self$m_Message, self$m_Progress,
            self$m_CurrentClusterCount, self$m_RetryCount, self$m_StreamingWindowSize,
            self$m_TotalInferences, self$m_TotalSamplesWritten)
    }, fromJSONString = function(MAmberStatusJson) {
        MAmberStatusObject <- jsonlite::fromJSON(MAmberStatusJson)
        VersionNumberObject <- VersionNumber$new()
        self$VersionNumber <- VersionNumberObject$fromJSON(jsonlite::toJSON(MAmberStatusObject$VersionNumber,
            auto_unbox = TRUE))
        self$m_Status <- MAmberStatusObject$m_Status
        self$m_Message <- MAmberStatusObject$m_Message
        self$m_Progress <- MAmberStatusObject$m_Progress
        self$m_CurrentClusterCount <- MAmberStatusObject$m_CurrentClusterCount
        self$m_RetryCount <- MAmberStatusObject$m_RetryCount
        self$m_StreamingWindowSize <- MAmberStatusObject$m_StreamingWindowSize
        self$m_TotalInferences <- MAmberStatusObject$m_TotalInferences
        self$m_TotalSamplesWritten <- MAmberStatusObject$m_TotalSamplesWritten
    }))
