# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MayContainNullsArray Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MayContainNullsArray <- R6::R6Class(
  'MayContainNullsArray',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      MayContainNullsArrayObject <- list()

      MayContainNullsArrayObject
    },
    fromJSON = function(MayContainNullsArrayJson) {
      MayContainNullsArrayObject <- jsonlite::fromJSON(MayContainNullsArrayJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(MayContainNullsArrayJson) {
      MayContainNullsArrayObject <- jsonlite::fromJSON(MayContainNullsArrayJson)
    }
  )
)
