# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MBufferStats Class
#'
#' @field VersionNumber 
#' @field TotalBytesWritten 
#' @field TotalBytesProcessed 
#' @field LoadBufferLength 
#' @field LoadBufferCapacity 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MBufferStats <- R6::R6Class("MBufferStats", public = list(VersionNumber = NULL, TotalBytesWritten = NULL,
    TotalBytesProcessed = NULL, LoadBufferLength = NULL, LoadBufferCapacity = NULL,
    initialize = function(VersionNumber, TotalBytesWritten, TotalBytesProcessed,
        LoadBufferLength, LoadBufferCapacity) {
        if (!missing(VersionNumber)) {
            stopifnot(R6::is.R6(VersionNumber))
            self$VersionNumber <- VersionNumber
        }
        if (!missing(TotalBytesWritten)) {
            stopifnot(is.numeric(TotalBytesWritten), length(TotalBytesWritten) ==
                1)
            self$TotalBytesWritten <- TotalBytesWritten
        }
        if (!missing(TotalBytesProcessed)) {
            stopifnot(is.numeric(TotalBytesProcessed), length(TotalBytesProcessed) ==
                1)
            self$TotalBytesProcessed <- TotalBytesProcessed
        }
        if (!missing(LoadBufferLength)) {
            stopifnot(is.numeric(LoadBufferLength), length(LoadBufferLength) == 1)
            self$LoadBufferLength <- LoadBufferLength
        }
        if (!missing(LoadBufferCapacity)) {
            stopifnot(is.numeric(LoadBufferCapacity), length(LoadBufferCapacity) ==
                1)
            self$LoadBufferCapacity <- LoadBufferCapacity
        }
    }, toJSON = function() {
        MBufferStatsObject <- list()
        if (!is.null(self$VersionNumber)) {
            MBufferStatsObject[["VersionNumber"]] <- self$VersionNumber$toJSON()
        }
        if (!is.null(self$TotalBytesWritten)) {
            MBufferStatsObject[["TotalBytesWritten"]] <- self$TotalBytesWritten
        }
        if (!is.null(self$TotalBytesProcessed)) {
            MBufferStatsObject[["TotalBytesProcessed"]] <- self$TotalBytesProcessed
        }
        if (!is.null(self$LoadBufferLength)) {
            MBufferStatsObject[["LoadBufferLength"]] <- self$LoadBufferLength
        }
        if (!is.null(self$LoadBufferCapacity)) {
            MBufferStatsObject[["LoadBufferCapacity"]] <- self$LoadBufferCapacity
        }

        MBufferStatsObject
    }, fromJSON = function(MBufferStatsJson) {
        MBufferStatsObject <- jsonlite::fromJSON(MBufferStatsJson)
        if (!is.null(MBufferStatsObject$VersionNumber)) {
            VersionNumberObject <- VersionNumber$new()
            VersionNumberObject$fromJSON(jsonlite::toJSON(MBufferStatsObject$VersionNumber,
                auto_unbox = TRUE))
            self$VersionNumber <- VersionNumberObject
        }
        if (!is.null(MBufferStatsObject$TotalBytesWritten)) {
            self$TotalBytesWritten <- MBufferStatsObject$TotalBytesWritten
        }
        if (!is.null(MBufferStatsObject$TotalBytesProcessed)) {
            self$TotalBytesProcessed <- MBufferStatsObject$TotalBytesProcessed
        }
        if (!is.null(MBufferStatsObject$LoadBufferLength)) {
            self$LoadBufferLength <- MBufferStatsObject$LoadBufferLength
        }
        if (!is.null(MBufferStatsObject$LoadBufferCapacity)) {
            self$LoadBufferCapacity <- MBufferStatsObject$LoadBufferCapacity
        }
    }, toJSONString = function() {
        sprintf("{
           \"VersionNumber\": %s,
           \"TotalBytesWritten\": %d,
           \"TotalBytesProcessed\": %d,
           \"LoadBufferLength\": %d,
           \"LoadBufferCapacity\": %d
        }",
            self$VersionNumber$toJSON(), self$TotalBytesWritten, self$TotalBytesProcessed,
            self$LoadBufferLength, self$LoadBufferCapacity)
    }, fromJSONString = function(MBufferStatsJson) {
        MBufferStatsObject <- jsonlite::fromJSON(MBufferStatsJson)
        VersionNumberObject <- VersionNumber$new()
        self$VersionNumber <- VersionNumberObject$fromJSON(jsonlite::toJSON(MBufferStatsObject$VersionNumber,
            auto_unbox = TRUE))
        self$TotalBytesWritten <- MBufferStatsObject$TotalBytesWritten
        self$TotalBytesProcessed <- MBufferStatsObject$TotalBytesProcessed
        self$LoadBufferLength <- MBufferStatsObject$LoadBufferLength
        self$LoadBufferCapacity <- MBufferStatsObject$LoadBufferCapacity
    }))
