# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MNanoBackend Class
#'
#' @field VersionNumber 
#' @field m_PatternMemory 
#' @field m_InitComplete 
#' @field m_PatternLength 
#' @field m_LearningIsOn 
#' @field m_NumOfPatternsClustered 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MNanoBackend <- R6::R6Class(
  'MNanoBackend',
  public = list(
    `VersionNumber` = NULL,
    `m_PatternMemory` = NULL,
    `m_InitComplete` = NULL,
    `m_PatternLength` = NULL,
    `m_LearningIsOn` = NULL,
    `m_NumOfPatternsClustered` = NULL,
    initialize = function(`VersionNumber`, `m_PatternMemory`, `m_InitComplete`, `m_PatternLength`, `m_LearningIsOn`, `m_NumOfPatternsClustered`){
      if (!missing(`VersionNumber`)) {
        stopifnot(R6::is.R6(`VersionNumber`))
        self$`VersionNumber` <- `VersionNumber`
      }
      if (!missing(`m_PatternMemory`)) {
        stopifnot(R6::is.R6(`m_PatternMemory`))
        self$`m_PatternMemory` <- `m_PatternMemory`
      }
      if (!missing(`m_InitComplete`)) {
        self$`m_InitComplete` <- `m_InitComplete`
      }
      if (!missing(`m_PatternLength`)) {
        stopifnot(is.numeric(`m_PatternLength`), length(`m_PatternLength`) == 1)
        self$`m_PatternLength` <- `m_PatternLength`
      }
      if (!missing(`m_LearningIsOn`)) {
        self$`m_LearningIsOn` <- `m_LearningIsOn`
      }
      if (!missing(`m_NumOfPatternsClustered`)) {
        stopifnot(is.numeric(`m_NumOfPatternsClustered`), length(`m_NumOfPatternsClustered`) == 1)
        self$`m_NumOfPatternsClustered` <- `m_NumOfPatternsClustered`
      }
    },
    toJSON = function() {
      MNanoBackendObject <- list()
      if (!is.null(self$`VersionNumber`)) {
        MNanoBackendObject[['VersionNumber']] <- self$`VersionNumber`$toJSON()
      }
      if (!is.null(self$`m_PatternMemory`)) {
        MNanoBackendObject[['m_PatternMemory']] <- self$`m_PatternMemory`$toJSON()
      }
      if (!is.null(self$`m_InitComplete`)) {
        MNanoBackendObject[['m_InitComplete']] <- self$`m_InitComplete`
      }
      if (!is.null(self$`m_PatternLength`)) {
        MNanoBackendObject[['m_PatternLength']] <- self$`m_PatternLength`
      }
      if (!is.null(self$`m_LearningIsOn`)) {
        MNanoBackendObject[['m_LearningIsOn']] <- self$`m_LearningIsOn`
      }
      if (!is.null(self$`m_NumOfPatternsClustered`)) {
        MNanoBackendObject[['m_NumOfPatternsClustered']] <- self$`m_NumOfPatternsClustered`
      }

      MNanoBackendObject
    },
    fromJSON = function(MNanoBackendJson) {
      MNanoBackendObject <- jsonlite::fromJSON(MNanoBackendJson, simplifyVector = FALSE)
      if (!is.null(MNanoBackendObject$`VersionNumber`)) {
        VersionNumberObject <- VersionNumber$new()
        VersionNumberObject$fromJSON(jsonlite::toJSON(MNanoBackendObject$VersionNumber, auto_unbox = TRUE))
        self$`VersionNumber` <- VersionNumberObject
      }
      if (!is.null(MNanoBackendObject$`m_PatternMemory`)) {
        m_PatternMemoryObject <- MPatternMemory$new()
        m_PatternMemoryObject$fromJSON(jsonlite::toJSON(MNanoBackendObject$m_PatternMemory, auto_unbox = TRUE))
        self$`m_PatternMemory` <- m_PatternMemoryObject
      }
      if (!is.null(MNanoBackendObject$`m_InitComplete`)) {
        self$`m_InitComplete` <- MNanoBackendObject$`m_InitComplete`
      }
      if (!is.null(MNanoBackendObject$`m_PatternLength`)) {
        self$`m_PatternLength` <- MNanoBackendObject$`m_PatternLength`
      }
      if (!is.null(MNanoBackendObject$`m_LearningIsOn`)) {
        self$`m_LearningIsOn` <- MNanoBackendObject$`m_LearningIsOn`
      }
      if (!is.null(MNanoBackendObject$`m_NumOfPatternsClustered`)) {
        self$`m_NumOfPatternsClustered` <- MNanoBackendObject$`m_NumOfPatternsClustered`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "VersionNumber": %s,
           "m_PatternMemory": %s,
           "m_InitComplete": %s,
           "m_PatternLength": %d,
           "m_LearningIsOn": %s,
           "m_NumOfPatternsClustered": %d
        }',
        self$`VersionNumber`$toJSON(),
        self$`m_PatternMemory`$toJSON(),
        self$`m_InitComplete`,
        self$`m_PatternLength`,
        self$`m_LearningIsOn`,
        self$`m_NumOfPatternsClustered`
      )
    },
    fromJSONString = function(MNanoBackendJson) {
      MNanoBackendObject <- jsonlite::fromJSON(MNanoBackendJson, simplifyVector = FALSE)
      VersionNumberObject <- VersionNumber$new()
      self$`VersionNumber` <- VersionNumberObject$fromJSON(jsonlite::toJSON(MNanoBackendObject$VersionNumber, auto_unbox = TRUE))
      MPatternMemoryObject <- MPatternMemory$new()
      self$`m_PatternMemory` <- MPatternMemoryObject$fromJSON(jsonlite::toJSON(MNanoBackendObject$m_PatternMemory, auto_unbox = TRUE))
      self$`m_InitComplete` <- MNanoBackendObject$`m_InitComplete`
      self$`m_PatternLength` <- MNanoBackendObject$`m_PatternLength`
      self$`m_LearningIsOn` <- MNanoBackendObject$`m_LearningIsOn`
      self$`m_NumOfPatternsClustered` <- MNanoBackendObject$`m_NumOfPatternsClustered`
    }
  )
)

