# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MPatternMemory Class
#'
#' @field VersionNumber 
#'
#' @importF
m R6 R6Class
#' @importF
m jsonlite f
mJSON toJSON
#' @export
MPatternMemory <- R6::R6Class("MPatternMemory", public = list(VersionNumber = NULL,
    initialize = function(VersionNumber) {
        if (!missing(VersionNumber)) {
            stopifnot(R6::is.R6(VersionNumber))
            self$VersionNumber <- VersionNumber
        }
    }, toJSON = function() {
        MPatternMemoryObject <- list()
        if (!is.null(self$VersionNumber)) {
            MPatternMemoryObject[["VersionNumber"]] <- self$VersionNumber$toJSON()
        }

        MPatternMemoryObject
    }, f
mJSON = function(MPatternMemoryJson) {
        MPatternMemoryObject <- jsonlite::f
mJSON(MPatternMemoryJson)
        if (!is.null(MPatternMemoryObject$VersionNumber)) {
            VersionNumberObject <- VersionNumber$new()
            VersionNumberObject$f
mJSON(jsonlite::toJSON(MPatternMemoryObject$VersionNumber,
                auto_unbox = TRUE))
            self$VersionNumber <- VersionNumberObject
        }
    }, toJSONString = function() {
        sprintf("{
           \"VersionNumber\": %s
        }", self$VersionNumber$toJSON())
    }, f
mJSONString = function(MPatternMemoryJson) {
        MPatternMemoryObject <- jsonlite::f
mJSON(MPatternMemoryJson)
        VersionNumberObject <- VersionNumber$new()
        self$VersionNumber <- VersionNumberObject$f
mJSON(jsonlite::toJSON(MPatternMemoryObject$VersionNumber,
            auto_unbox = TRUE))
    }))
