# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MRecentIDs Class
#'
#' @field VersionNumber 
#' @field m_Values 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MRecentIDs <- R6::R6Class("MRecentIDs", public = list(VersionNumber = NULL, m_Values = NULL,
    initialize = function(VersionNumber, m_Values) {
        if (!missing(VersionNumber)) {
            stopifnot(R6::is.R6(VersionNumber))
            self$VersionNumber <- VersionNumber
        }
        if (!missing(m_Values)) {
            stopifnot(is.list(m_Values), length(m_Values) != 0)
            lapply(m_Values, function(x) stopifnot(is.character(x)))
            self$m_Values <- m_Values
        }
    }, toJSON = function() {
        MRecentIDsObject <- list()
        if (!is.null(self$VersionNumber)) {
            MRecentIDsObject[["VersionNumber"]] <- self$VersionNumber$toJSON()
        }
        if (!is.null(self$m_Values)) {
            MRecentIDsObject[["m_Values"]] <- self$m_Values
        }

        MRecentIDsObject
    }, fromJSON = function(MRecentIDsJson) {
        MRecentIDsObject <- jsonlite::fromJSON(MRecentIDsJson)
        if (!is.null(MRecentIDsObject$VersionNumber)) {
            VersionNumberObject <- VersionNumber$new()
            VersionNumberObject$fromJSON(jsonlite::toJSON(MRecentIDsObject$VersionNumber,
                auto_unbox = TRUE))
            self$VersionNumber <- VersionNumberObject
        }
        if (!is.null(MRecentIDsObject$m_Values)) {
            self$m_Values <- MRecentIDsObject$m_Values
        }
    }, toJSONString = function() {
        sprintf("{
           \"VersionNumber\": %s,
           \"m_Values\": [%s]
        }",
            self$VersionNumber$toJSON(), lapply(self$m_Values, function(x) paste(paste0("\"",
                x, "\""), sep = ",")))
    }, fromJSONString = function(MRecentIDsJson) {
        MRecentIDsObject <- jsonlite::fromJSON(MRecentIDsJson)
        VersionNumberObject <- VersionNumber$new()
        self$VersionNumber <- VersionNumberObject$fromJSON(jsonlite::toJSON(MRecentIDsObject$VersionNumber,
            auto_unbox = TRUE))
        self$m_Values <- MRecentIDsObject$m_Values
    }))
