# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MRecentAnalytics Class
#'
#' @field VersionNumber 
#' @field m_Values 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MRecentAnalytics <- R6::R6Class("MRecentAnalytics", public = list(VersionNumber = NULL,
    m_Values = NULL, initialize = function(VersionNumber, m_Values) {
        if (!missing(VersionNumber)) {
            stopifnot(R6::is.R6(VersionNumber))
            self$VersionNumber <- VersionNumber
        }
        if (!missing(m_Values)) {
            stopifnot(is.list(m_Values), length(m_Values) != 0)
            lapply(m_Values, function(x) stopifnot(is.character(x)))
            self$m_Values <- m_Values
        }
    }, toJSON = function() {
        MRecentAnalyticsObject <- list()
        if (!is.null(self$VersionNumber)) {
            MRecentAnalyticsObject[["VersionNumber"]] <- self$VersionNumber$toJSON()
        }
        if (!is.null(self$m_Values)) {
            MRecentAnalyticsObject[["m_Values"]] <- self$m_Values
        }

        MRecentAnalyticsObject
    }, fromJSON = function(MRecentAnalyticsJson) {
        MRecentAnalyticsObject <- jsonlite::fromJSON(MRecentAnalyticsJson)
        if (!is.null(MRecentAnalyticsObject$VersionNumber)) {
            VersionNumberObject <- VersionNumber$new()
            VersionNumberObject$fromJSON(jsonlite::toJSON(MRecentAnalyticsObject$VersionNumber,
                auto_unbox = TRUE))
            self$VersionNumber <- VersionNumberObject
        }
        if (!is.null(MRecentAnalyticsObject$m_Values)) {
            self$m_Values <- MRecentAnalyticsObject$m_Values
        }
    }, toJSONString = function() {
        sprintf("{
           \"VersionNumber\": %s,
           \"m_Values\": [%s]
        }",
            self$VersionNumber$toJSON(), lapply(self$m_Values, function(x) paste(paste0("\"",
                x, "\""), sep = ",")))
    }, fromJSONString = function(MRecentAnalyticsJson) {
        MRecentAnalyticsObject <- jsonlite::fromJSON(MRecentAnalyticsJson)
        VersionNumberObject <- VersionNumber$new()
        self$VersionNumber <- VersionNumberObject$fromJSON(jsonlite::toJSON(MRecentAnalyticsObject$VersionNumber,
            auto_unbox = TRUE))
        self$m_Values <- MRecentAnalyticsObject$m_Values
    }))
