# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MRecentSamples Class
#'
#' @field VersionNumber 
#' @field m_Values 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MRecentSamples <- R6::R6Class(
  'MRecentSamples',
  public = list(
    `VersionNumber` = NULL,
    `m_Values` = NULL,
    initialize = function(`VersionNumber`, `m_Values`){
      if (!missing(`VersionNumber`)) {
        stopifnot(R6::is.R6(`VersionNumber`))
        self$`VersionNumber` <- `VersionNumber`
      }
      if (!missing(`m_Values`)) {
        stopifnot(is.list(`m_Values`), length(`m_Values`) != 0)
        lapply(`m_Values`, function(x) stopifnot(R6::is.R6(x)))
        self$`m_Values` <- `m_Values`
      }
    },
    toJSON = function() {
      MRecentSamplesObject <- list()
      if (!is.null(self$`VersionNumber`)) {
        MRecentSamplesObject[['VersionNumber']] <- self$`VersionNumber`$toJSON()
      }
      if (!is.null(self$`m_Values`)) {
        MRecentSamplesObject[['m_Values']] <- lapply(self$`m_Values`, function(x) x$toJSON())
      }

      MRecentSamplesObject
    },
    fromJSON = function(MRecentSamplesJson) {
      MRecentSamplesObject <- jsonlite::fromJSON(MRecentSamplesJson)
      if (!is.null(MRecentSamplesObject$`VersionNumber`)) {
        VersionNumberObject <- VersionNumber$new()
        VersionNumberObject$fromJSON(jsonlite::toJSON(MRecentSamplesObject$VersionNumber, auto_unbox = TRUE))
        self$`VersionNumber` <- VersionNumberObject
      }
      if (!is.null(MRecentSamplesObject$`m_Values`)) {
        self$`m_Values` <- lapply(MRecentSamplesObject$`m_Values`, function(x) {
          m_ValuesObject <- Numeric$new()
          m_ValuesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          m_ValuesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "VersionNumber": %s,
           "m_Values": [%s]
        }',
        self$`VersionNumber`$toJSON(),
        lapply(self$`m_Values`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(MRecentSamplesJson) {
      MRecentSamplesObject <- jsonlite::fromJSON(MRecentSamplesJson)
      VersionNumberObject <- VersionNumber$new()
      self$`VersionNumber` <- VersionNumberObject$fromJSON(jsonlite::toJSON(MRecentSamplesObject$VersionNumber, auto_unbox = TRUE))
      self$`m_Values` <- lapply(MRecentSamplesObject$`m_Values`, function(x) Numeric$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
