# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MTraining Class
#'
#' @field VersionNumber 
#' @field m_GeometricPlotY 
#' @field m_GeometricPlotX 
#' @field m_ClusterGrowth 
#' @field m_AnomalyIndexes 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MTraining <- R6::R6Class(
  'MTraining',
  public = list(
    `VersionNumber` = NULL,
    `m_GeometricPlotY` = NULL,
    `m_GeometricPlotX` = NULL,
    `m_ClusterGrowth` = NULL,
    `m_AnomalyIndexes` = NULL,
    initialize = function(`VersionNumber`, `m_GeometricPlotY`, `m_GeometricPlotX`, `m_ClusterGrowth`, `m_AnomalyIndexes`){
      if (!missing(`VersionNumber`)) {
        stopifnot(is.list(`VersionNumber`), length(`VersionNumber`) != 0)
        lapply(`VersionNumber`, function(x) stopifnot(R6::is.R6(x)))
        self$`VersionNumber` <- `VersionNumber`
      }
      if (!missing(`m_GeometricPlotY`)) {
        stopifnot(is.list(`m_GeometricPlotY`), length(`m_GeometricPlotY`) != 0)
        lapply(`m_GeometricPlotY`, function(x) stopifnot(is.character(x)))
        self$`m_GeometricPlotY` <- `m_GeometricPlotY`
      }
      if (!missing(`m_GeometricPlotX`)) {
        stopifnot(is.list(`m_GeometricPlotX`), length(`m_GeometricPlotX`) != 0)
        lapply(`m_GeometricPlotX`, function(x) stopifnot(is.character(x)))
        self$`m_GeometricPlotX` <- `m_GeometricPlotX`
      }
      if (!missing(`m_ClusterGrowth`)) {
        stopifnot(is.list(`m_ClusterGrowth`), length(`m_ClusterGrowth`) != 0)
        lapply(`m_ClusterGrowth`, function(x) stopifnot(is.character(x)))
        self$`m_ClusterGrowth` <- `m_ClusterGrowth`
      }
      if (!missing(`m_AnomalyIndexes`)) {
        stopifnot(is.list(`m_AnomalyIndexes`), length(`m_AnomalyIndexes`) != 0)
        lapply(`m_AnomalyIndexes`, function(x) stopifnot(is.character(x)))
        self$`m_AnomalyIndexes` <- `m_AnomalyIndexes`
      }
    },
    toJSON = function() {
      MTrainingObject <- list()
      if (!is.null(self$`VersionNumber`)) {
        MTrainingObject[['VersionNumber']] <- lapply(self$`VersionNumber`, function(x) x$toJSON())
      }
      if (!is.null(self$`m_GeometricPlotY`)) {
        MTrainingObject[['m_GeometricPlotY']] <- self$`m_GeometricPlotY`
      }
      if (!is.null(self$`m_GeometricPlotX`)) {
        MTrainingObject[['m_GeometricPlotX']] <- self$`m_GeometricPlotX`
      }
      if (!is.null(self$`m_ClusterGrowth`)) {
        MTrainingObject[['m_ClusterGrowth']] <- self$`m_ClusterGrowth`
      }
      if (!is.null(self$`m_AnomalyIndexes`)) {
        MTrainingObject[['m_AnomalyIndexes']] <- self$`m_AnomalyIndexes`
      }

      MTrainingObject
    },
    fromJSON = function(MTrainingJson) {
      MTrainingObject <- jsonlite::fromJSON(MTrainingJson, simplifyVector = FALSE)
      if (!is.null(MTrainingObject$`VersionNumber`)) {
        self$`VersionNumber` <- lapply(MTrainingObject$`VersionNumber`, function(x) {
          VersionNumberObject <- VersionNumber$new()
          VersionNumberObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          VersionNumberObject
        })
      }
      if (!is.null(MTrainingObject$`m_GeometricPlotY`)) {
        self$`m_GeometricPlotY` <- MTrainingObject$`m_GeometricPlotY`
      }
      if (!is.null(MTrainingObject$`m_GeometricPlotX`)) {
        self$`m_GeometricPlotX` <- MTrainingObject$`m_GeometricPlotX`
      }
      if (!is.null(MTrainingObject$`m_ClusterGrowth`)) {
        self$`m_ClusterGrowth` <- MTrainingObject$`m_ClusterGrowth`
      }
      if (!is.null(MTrainingObject$`m_AnomalyIndexes`)) {
        self$`m_AnomalyIndexes` <- MTrainingObject$`m_AnomalyIndexes`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "VersionNumber": [%s],
           "m_GeometricPlotY": [%s],
           "m_GeometricPlotX": [%s],
           "m_ClusterGrowth": [%s],
           "m_AnomalyIndexes": [%s]
        }',
        lapply(self$`VersionNumber`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`m_GeometricPlotY`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`m_GeometricPlotX`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`m_ClusterGrowth`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`m_AnomalyIndexes`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(MTrainingJson) {
      MTrainingObject <- jsonlite::fromJSON(MTrainingJson, simplifyVector = FALSE)
      self$`VersionNumber` <- lapply(MTrainingObject$`VersionNumber`, function(x) VersionNumber$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`m_GeometricPlotY` <- MTrainingObject$`m_GeometricPlotY`
      self$`m_GeometricPlotX` <- MTrainingObject$`m_GeometricPlotX`
      self$`m_ClusterGrowth` <- MTrainingObject$`m_ClusterGrowth`
      self$`m_AnomalyIndexes` <- MTrainingObject$`m_AnomalyIndexes`
    }
  )
)

