# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PCA Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PCA <- R6::R6Class(
  'PCA',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      PCAObject <- list()

      PCAObject
    },
    fromJSON = function(PCAJson) {
      PCAObject <- jsonlite::fromJSON(PCAJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(PCAJson) {
      PCAObject <- jsonlite::fromJSON(PCAJson)
    }
  )
)
