# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PostStreamResponse Class
#'
#' @field state 
#' @field message 
#' @field progress 
#' @field clusterCount 
#' @field retryCount 
#' @field streamingWindowSize 
#' @field totalInferences 
#' @field RI 
#' @field SI 
#' @field AD 
#' @field AH 
#' @field AM 
#' @field AW 
#' @field ID 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PostStreamResponse <- R6::R6Class(
  'PostStreamResponse',
  public = list(
    `state` = NULL,
    `message` = NULL,
    `progress` = NULL,
    `clusterCount` = NULL,
    `retryCount` = NULL,
    `streamingWindowSize` = NULL,
    `totalInferences` = NULL,
    `RI` = NULL,
    `SI` = NULL,
    `AD` = NULL,
    `AH` = NULL,
    `AM` = NULL,
    `AW` = NULL,
    `ID` = NULL,
    initialize = function(`state`, `message`, `progress`, `clusterCount`, `retryCount`, `streamingWindowSize`, `totalInferences`, `RI`, `SI`, `AD`, `AH`, `AM`, `AW`, `ID`){
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`progress`)) {
        stopifnot(is.numeric(`progress`), length(`progress`) == 1)
        stopifnot(R6::is.R6(`progress`))
        self$`progress` <- `progress`
      }
      if (!missing(`clusterCount`)) {
        stopifnot(is.numeric(`clusterCount`), length(`clusterCount`) == 1)
        stopifnot(R6::is.R6(`clusterCount`))
        self$`clusterCount` <- `clusterCount`
      }
      if (!missing(`retryCount`)) {
        stopifnot(is.numeric(`retryCount`), length(`retryCount`) == 1)
        stopifnot(R6::is.R6(`retryCount`))
        self$`retryCount` <- `retryCount`
      }
      if (!missing(`streamingWindowSize`)) {
        stopifnot(is.numeric(`streamingWindowSize`), length(`streamingWindowSize`) == 1)
        stopifnot(R6::is.R6(`streamingWindowSize`))
        self$`streamingWindowSize` <- `streamingWindowSize`
      }
      if (!missing(`totalInferences`)) {
        stopifnot(is.numeric(`totalInferences`), length(`totalInferences`) == 1)
        stopifnot(R6::is.R6(`totalInferences`))
        self$`totalInferences` <- `totalInferences`
      }
      if (!missing(`RI`)) {
        stopifnot(R6::is.R6(`RI`))
        self$`RI` <- `RI`
      }
      if (!missing(`SI`)) {
        stopifnot(R6::is.R6(`SI`))
        self$`SI` <- `SI`
      }
      if (!missing(`AD`)) {
        stopifnot(R6::is.R6(`AD`))
        self$`AD` <- `AD`
      }
      if (!missing(`AH`)) {
        stopifnot(R6::is.R6(`AH`))
        self$`AH` <- `AH`
      }
      if (!missing(`AM`)) {
        stopifnot(R6::is.R6(`AM`))
        self$`AM` <- `AM`
      }
      if (!missing(`AW`)) {
        stopifnot(R6::is.R6(`AW`))
        self$`AW` <- `AW`
      }
      if (!missing(`ID`)) {
        stopifnot(R6::is.R6(`ID`))
        self$`ID` <- `ID`
      }
    },
    toJSON = function() {
      PostStreamResponseObject <- list()
      if (!is.null(self$`state`)) {
        PostStreamResponseObject[['state']] <- self$`state`
      }
      if (!is.null(self$`message`)) {
        PostStreamResponseObject[['message']] <- self$`message`
      }
      if (!is.null(self$`progress`)) {
        PostStreamResponseObject[['progress']] <- self$`progress`$toJSON()
      }
      if (!is.null(self$`clusterCount`)) {
        PostStreamResponseObject[['clusterCount']] <- self$`clusterCount`$toJSON()
      }
      if (!is.null(self$`retryCount`)) {
        PostStreamResponseObject[['retryCount']] <- self$`retryCount`$toJSON()
      }
      if (!is.null(self$`streamingWindowSize`)) {
        PostStreamResponseObject[['streamingWindowSize']] <- self$`streamingWindowSize`$toJSON()
      }
      if (!is.null(self$`totalInferences`)) {
        PostStreamResponseObject[['totalInferences']] <- self$`totalInferences`$toJSON()
      }
      if (!is.null(self$`RI`)) {
        PostStreamResponseObject[['RI']] <- self$`RI`$toJSON()
      }
      if (!is.null(self$`SI`)) {
        PostStreamResponseObject[['SI']] <- self$`SI`$toJSON()
      }
      if (!is.null(self$`AD`)) {
        PostStreamResponseObject[['AD']] <- self$`AD`$toJSON()
      }
      if (!is.null(self$`AH`)) {
        PostStreamResponseObject[['AH']] <- self$`AH`$toJSON()
      }
      if (!is.null(self$`AM`)) {
        PostStreamResponseObject[['AM']] <- self$`AM`$toJSON()
      }
      if (!is.null(self$`AW`)) {
        PostStreamResponseObject[['AW']] <- self$`AW`$toJSON()
      }
      if (!is.null(self$`ID`)) {
        PostStreamResponseObject[['ID']] <- self$`ID`$toJSON()
      }

      PostStreamResponseObject
    },
    fromJSON = function(PostStreamResponseJson) {
      PostStreamResponseObject <- jsonlite::fromJSON(PostStreamResponseJson)
      if (!is.null(PostStreamResponseObject$`state`)) {
        self$`state` <- PostStreamResponseObject$`state`
      }
      if (!is.null(PostStreamResponseObject$`message`)) {
        self$`message` <- PostStreamResponseObject$`message`
      }
      if (!is.null(PostStreamResponseObject$`progress`)) {
        progressObject <- BigDecimal$new()
        progressObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$progress, auto_unbox = TRUE))
        self$`progress` <- progressObject
      }
      if (!is.null(PostStreamResponseObject$`clusterCount`)) {
        clusterCountObject <- BigDecimal$new()
        clusterCountObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$clusterCount, auto_unbox = TRUE))
        self$`clusterCount` <- clusterCountObject
      }
      if (!is.null(PostStreamResponseObject$`retryCount`)) {
        retryCountObject <- BigDecimal$new()
        retryCountObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$retryCount, auto_unbox = TRUE))
        self$`retryCount` <- retryCountObject
      }
      if (!is.null(PostStreamResponseObject$`streamingWindowSize`)) {
        streamingWindowSizeObject <- BigDecimal$new()
        streamingWindowSizeObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$streamingWindowSize, auto_unbox = TRUE))
        self$`streamingWindowSize` <- streamingWindowSizeObject
      }
      if (!is.null(PostStreamResponseObject$`totalInferences`)) {
        totalInferencesObject <- BigDecimal$new()
        totalInferencesObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$totalInferences, auto_unbox = TRUE))
        self$`totalInferences` <- totalInferencesObject
      }
      if (!is.null(PostStreamResponseObject$`RI`)) {
        RIObject <- Uint16Array$new()
        RIObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$RI, auto_unbox = TRUE))
        self$`RI` <- RIObject
      }
      if (!is.null(PostStreamResponseObject$`SI`)) {
        SIObject <- Uint16Array$new()
        SIObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$SI, auto_unbox = TRUE))
        self$`SI` <- SIObject
      }
      if (!is.null(PostStreamResponseObject$`AD`)) {
        ADObject <- Uint16Array$new()
        ADObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$AD, auto_unbox = TRUE))
        self$`AD` <- ADObject
      }
      if (!is.null(PostStreamResponseObject$`AH`)) {
        AHObject <- Uint16Array$new()
        AHObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$AH, auto_unbox = TRUE))
        self$`AH` <- AHObject
      }
      if (!is.null(PostStreamResponseObject$`AM`)) {
        AMObject <- Float32Array$new()
        AMObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$AM, auto_unbox = TRUE))
        self$`AM` <- AMObject
      }
      if (!is.null(PostStreamResponseObject$`AW`)) {
        AWObject <- Uint16Array$new()
        AWObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$AW, auto_unbox = TRUE))
        self$`AW` <- AWObject
      }
      if (!is.null(PostStreamResponseObject$`ID`)) {
        IDObject <- Int32Array$new()
        IDObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$ID, auto_unbox = TRUE))
        self$`ID` <- IDObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "state": %s,
           "message": %s,
           "progress": %s,
           "clusterCount": %s,
           "retryCount": %s,
           "streamingWindowSize": %s,
           "totalInferences": %s,
           "RI": %s,
           "SI": %s,
           "AD": %s,
           "AH": %s,
           "AM": %s,
           "AW": %s,
           "ID": %s
        }',
        self$`state`,
        self$`message`,
        self$`progress`$toJSON(),
        self$`clusterCount`$toJSON(),
        self$`retryCount`$toJSON(),
        self$`streamingWindowSize`$toJSON(),
        self$`totalInferences`$toJSON(),
        self$`RI`$toJSON(),
        self$`SI`$toJSON(),
        self$`AD`$toJSON(),
        self$`AH`$toJSON(),
        self$`AM`$toJSON(),
        self$`AW`$toJSON(),
        self$`ID`$toJSON()
      )
    },
    fromJSONString = function(PostStreamResponseJson) {
      PostStreamResponseObject <- jsonlite::fromJSON(PostStreamResponseJson)
      self$`state` <- PostStreamResponseObject$`state`
      self$`message` <- PostStreamResponseObject$`message`
      BigDecimalObject <- BigDecimal$new()
      self$`progress` <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$progress, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`clusterCount` <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$clusterCount, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`retryCount` <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$retryCount, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`streamingWindowSize` <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$streamingWindowSize, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`totalInferences` <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$totalInferences, auto_unbox = TRUE))
      Uint16ArrayObject <- Uint16Array$new()
      self$`RI` <- Uint16ArrayObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$RI, auto_unbox = TRUE))
      Uint16ArrayObject <- Uint16Array$new()
      self$`SI` <- Uint16ArrayObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$SI, auto_unbox = TRUE))
      Uint16ArrayObject <- Uint16Array$new()
      self$`AD` <- Uint16ArrayObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$AD, auto_unbox = TRUE))
      Uint16ArrayObject <- Uint16Array$new()
      self$`AH` <- Uint16ArrayObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$AH, auto_unbox = TRUE))
      Float32ArrayObject <- Float32Array$new()
      self$`AM` <- Float32ArrayObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$AM, auto_unbox = TRUE))
      Uint16ArrayObject <- Uint16Array$new()
      self$`AW` <- Uint16ArrayObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$AW, auto_unbox = TRUE))
      Int32ArrayObject <- Int32Array$new()
      self$`ID` <- Int32ArrayObject$fromJSON(jsonlite::toJSON(PostStreamResponseObject$ID, auto_unbox = TRUE))
    }
  )
)
