# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PostSensorRequest Class
#'
#' @field label 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PostSensorRequest <- R6::R6Class(
  'PostSensorRequest',
  public = list(
    `label` = NULL,
    initialize = function(`label`){
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
    },
    toJSON = function() {
      PostSensorRequestObject <- list()
      if (!is.null(self$`label`)) {
        PostSensorRequestObject[['label']] <- self$`label`
      }

      PostSensorRequestObject
    },
    fromJSON = function(PostSensorRequestJson) {
      PostSensorRequestObject <- jsonlite::fromJSON(PostSensorRequestJson)
      if (!is.null(PostSensorRequestObject$`label`)) {
        self$`label` <- PostSensorRequestObject$`label`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "label": %s
        }',
        self$`label`
      )
    },
    fromJSONString = function(PostSensorRequestJson) {
      PostSensorRequestObject <- jsonlite::fromJSON(PostSensorRequestJson)
      self$`label` <- PostSensorRequestObject$`label`
    }
  )
)
