# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PostConfigRequest Class
#'
#' @field anomalyHistoryWindow 
#' @field learningRateNumerator 
#' @field learningRateDenominator 
#' @field learningMaxClusters 
#' @field learningMaxSamples 
#' @field featureCount 
#' @field streamingWindowSize 
#' @field features 
#' @field samplesToBuffer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PostConfigRequest <- R6::R6Class("PostConfigRequest", public = list(anomalyHistoryWindow = NULL,
    learningRateNumerator = NULL, learningRateDenominator = NULL, learningMaxClusters = NULL,
    learningMaxSamples = NULL, featureCount = NULL, streamingWindowSize = NULL, features = NULL,
    samplesToBuffer = NULL, initialize = function(anomalyHistoryWindow, learningRateNumerator,
        learningRateDenominator, learningMaxClusters, learningMaxSamples, featureCount,
        streamingWindowSize, features, samplesToBuffer) {
        if (!missing(anomalyHistoryWindow)) {
            stopifnot(is.numeric(anomalyHistoryWindow), length(anomalyHistoryWindow) ==
                1)
            stopifnot(R6::is.R6(anomalyHistoryWindow))
            self$anomalyHistoryWindow <- anomalyHistoryWindow
        }
        if (!missing(learningRateNumerator)) {
            stopifnot(is.numeric(learningRateNumerator), length(learningRateNumerator) ==
                1)
            stopifnot(R6::is.R6(learningRateNumerator))
            self$learningRateNumerator <- learningRateNumerator
        }
        if (!missing(learningRateDenominator)) {
            stopifnot(is.numeric(learningRateDenominator), length(learningRateDenominator) ==
                1)
            stopifnot(R6::is.R6(learningRateDenominator))
            self$learningRateDenominator <- learningRateDenominator
        }
        if (!missing(learningMaxClusters)) {
            stopifnot(is.numeric(learningMaxClusters), length(learningMaxClusters) ==
                1)
            stopifnot(R6::is.R6(learningMaxClusters))
            self$learningMaxClusters <- learningMaxClusters
        }
        if (!missing(learningMaxSamples)) {
            stopifnot(is.numeric(learningMaxSamples), length(learningMaxSamples) ==
                1)
            stopifnot(R6::is.R6(learningMaxSamples))
            self$learningMaxSamples <- learningMaxSamples
        }
        if (!missing(featureCount)) {
            stopifnot(is.numeric(featureCount), length(featureCount) == 1)
            self$featureCount <- featureCount
        }
        if (!missing(streamingWindowSize)) {
            stopifnot(is.numeric(streamingWindowSize), length(streamingWindowSize) ==
                1)
            self$streamingWindowSize <- streamingWindowSize
        }
        if (!missing(features)) {
            stopifnot(is.list(features), length(features) != 0)
            lapply(features, function(x) stopifnot(R6::is.R6(x)))
            self$features <- features
        }
        if (!missing(samplesToBuffer)) {
            stopifnot(is.numeric(samplesToBuffer), length(samplesToBuffer) == 1)
            stopifnot(R6::is.R6(samplesToBuffer))
            self$samplesToBuffer <- samplesToBuffer
        }
    }, toJSON = function() {
        PostConfigRequestObject <- list()
        if (!is.null(self$anomalyHistoryWindow)) {
            PostConfigRequestObject[["anomalyHistoryWindow"]] <- self$anomalyHistoryWindow$toJSON()
        }
        if (!is.null(self$learningRateNumerator)) {
            PostConfigRequestObject[["learningRateNumerator"]] <- self$learningRateNumerator$toJSON()
        }
        if (!is.null(self$learningRateDenominator)) {
            PostConfigRequestObject[["learningRateDenominator"]] <- self$learningRateDenominator$toJSON()
        }
        if (!is.null(self$learningMaxClusters)) {
            PostConfigRequestObject[["learningMaxClusters"]] <- self$learningMaxClusters$toJSON()
        }
        if (!is.null(self$learningMaxSamples)) {
            PostConfigRequestObject[["learningMaxSamples"]] <- self$learningMaxSamples$toJSON()
        }
        if (!is.null(self$featureCount)) {
            PostConfigRequestObject[["featureCount"]] <- self$featureCount
        }
        if (!is.null(self$streamingWindowSize)) {
            PostConfigRequestObject[["streamingWindowSize"]] <- self$streamingWindowSize
        }
        if (!is.null(self$features)) {
            PostConfigRequestObject[["features"]] <- lapply(self$features, function(x) x$toJSON())
        }
        if (!is.null(self$samplesToBuffer)) {
            PostConfigRequestObject[["samplesToBuffer"]] <- self$samplesToBuffer$toJSON()
        }

        PostConfigRequestObject
    }, fromJSON = function(PostConfigRequestJson) {
        PostConfigRequestObject <- jsonlite::fromJSON(PostConfigRequestJson)
        if (!is.null(PostConfigRequestObject$anomalyHistoryWindow)) {
            anomalyHistoryWindowObject <- BigDecimal$new()
            anomalyHistoryWindowObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$anomalyHistoryWindow,
                auto_unbox = TRUE))
            self$anomalyHistoryWindow <- anomalyHistoryWindowObject
        }
        if (!is.null(PostConfigRequestObject$learningRateNumerator)) {
            learningRateNumeratorObject <- BigDecimal$new()
            learningRateNumeratorObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$learningRateNumerator,
                auto_unbox = TRUE))
            self$learningRateNumerator <- learningRateNumeratorObject
        }
        if (!is.null(PostConfigRequestObject$learningRateDenominator)) {
            learningRateDenominatorObject <- BigDecimal$new()
            learningRateDenominatorObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$learningRateDenominator,
                auto_unbox = TRUE))
            self$learningRateDenominator <- learningRateDenominatorObject
        }
        if (!is.null(PostConfigRequestObject$learningMaxClusters)) {
            learningMaxClustersObject <- BigDecimal$new()
            learningMaxClustersObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$learningMaxClusters,
                auto_unbox = TRUE))
            self$learningMaxClusters <- learningMaxClustersObject
        }
        if (!is.null(PostConfigRequestObject$learningMaxSamples)) {
            learningMaxSamplesObject <- BigDecimal$new()
            learningMaxSamplesObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$learningMaxSamples,
                auto_unbox = TRUE))
            self$learningMaxSamples <- learningMaxSamplesObject
        }
        if (!is.null(PostConfigRequestObject$featureCount)) {
            self$featureCount <- PostConfigRequestObject$featureCount
        }
        if (!is.null(PostConfigRequestObject$streamingWindowSize)) {
            self$streamingWindowSize <- PostConfigRequestObject$streamingWindowSize
        }
        if (!is.null(PostConfigRequestObject$features)) {
            self$features <- lapply(PostConfigRequestObject$features, function(x) {
                featuresObject <- FeatureConfig$new()
                featuresObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
                featuresObject
            })
        }
        if (!is.null(PostConfigRequestObject$samplesToBuffer)) {
            samplesToBufferObject <- BigDecimal$new()
            samplesToBufferObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$samplesToBuffer,
                auto_unbox = TRUE))
            self$samplesToBuffer <- samplesToBufferObject
        }
    }, toJSONString = function() {
        sprintf("{
           \"anomalyHistoryWindow\": %s,
           \"learningRateNumerator\": %s,
           \"learningRateDenominator\": %s,
           \"learningMaxClusters\": %s,
           \"learningMaxSamples\": %s,
           \"featureCount\": %d,
           \"streamingWindowSize\": %d,
           \"features\": [%s],
           \"samplesToBuffer\": %s
        }",
            self$anomalyHistoryWindow$toJSON(), self$learningRateNumerator$toJSON(),
            self$learningRateDenominator$toJSON(), self$learningMaxClusters$toJSON(),
            self$learningMaxSamples$toJSON(), self$featureCount, self$streamingWindowSize,
            lapply(self$features, function(x) paste(x$toJSON(), sep = ",")), self$samplesToBuffer$toJSON())
    }, fromJSONString = function(PostConfigRequestJson) {
        PostConfigRequestObject <- jsonlite::fromJSON(PostConfigRequestJson)
        BigDecimalObject <- BigDecimal$new()
        self$anomalyHistoryWindow <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$anomalyHistoryWindow,
            auto_unbox = TRUE))
        BigDecimalObject <- BigDecimal$new()
        self$learningRateNumerator <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$learningRateNumerator,
            auto_unbox = TRUE))
        BigDecimalObject <- BigDecimal$new()
        self$learningRateDenominator <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$learningRateDenominator,
            auto_unbox = TRUE))
        BigDecimalObject <- BigDecimal$new()
        self$learningMaxClusters <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$learningMaxClusters,
            auto_unbox = TRUE))
        BigDecimalObject <- BigDecimal$new()
        self$learningMaxSamples <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$learningMaxSamples,
            auto_unbox = TRUE))
        self$featureCount <- PostConfigRequestObject$featureCount
        self$streamingWindowSize <- PostConfigRequestObject$streamingWindowSize
        self$features <- lapply(PostConfigRequestObject$features, function(x) FeatureConfig$new()$fromJSON(jsonlite::toJSON(x,
            auto_unbox = TRUE)))
        BigDecimalObject <- BigDecimal$new()
        self$samplesToBuffer <- BigDecimalObject$fromJSON(jsonlite::toJSON(PostConfigRequestObject$samplesToBuffer,
            auto_unbox = TRUE))
    }))
