# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PostStreamResponse Class
#'
#' @field state 
#' @field message 
#' @field progress 
#' @field clusterCount 
#' @field retryCount 
#' @field streamingWindowSize 
#' @field totalInferences 
#' @field RI 
#' @field SI 
#' @field AD 
#' @field AH 
#' @field AM 
#' @field AW 
#' @field ID 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PostStreamResponse <- R6::R6Class(
  'PostStreamResponse',
  public = list(
    `state` = NULL,
    `message` = NULL,
    `progress` = NULL,
    `clusterCount` = NULL,
    `retryCount` = NULL,
    `streamingWindowSize` = NULL,
    `totalInferences` = NULL,
    `RI` = NULL,
    `SI` = NULL,
    `AD` = NULL,
    `AH` = NULL,
    `AM` = NULL,
    `AW` = NULL,
    `ID` = NULL,
    initialize = function(`state`, `message`, `progress`, `clusterCount`, `retryCount`, `streamingWindowSize`, `totalInferences`, `RI`, `SI`, `AD`, `AH`, `AM`, `AW`, `ID`){
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`progress`)) {
        stopifnot(is.numeric(`progress`), length(`progress`) == 1)
        stopifnot(R6::is.R6(`progress`))
        self$`progress` <- `progress`
      }
      if (!missing(`clusterCount`)) {
        stopifnot(is.numeric(`clusterCount`), length(`clusterCount`) == 1)
        stopifnot(R6::is.R6(`clusterCount`))
        self$`clusterCount` <- `clusterCount`
      }
      if (!missing(`retryCount`)) {
        stopifnot(is.numeric(`retryCount`), length(`retryCount`) == 1)
        stopifnot(R6::is.R6(`retryCount`))
        self$`retryCount` <- `retryCount`
      }
      if (!missing(`streamingWindowSize`)) {
        stopifnot(is.numeric(`streamingWindowSize`), length(`streamingWindowSize`) == 1)
        stopifnot(R6::is.R6(`streamingWindowSize`))
        self$`streamingWindowSize` <- `streamingWindowSize`
      }
      if (!missing(`totalInferences`)) {
        stopifnot(is.numeric(`totalInferences`), length(`totalInferences`) == 1)
        stopifnot(R6::is.R6(`totalInferences`))
        self$`totalInferences` <- `totalInferences`
      }
      if (!missing(`RI`)) {
        stopifnot(R6::is.R6(`RI`))
        self$`RI` <- `RI`
      }
      if (!missing(`SI`)) {
        stopifnot(R6::is.R6(`SI`))
        self$`SI` <- `SI`
      }
      if (!missing(`AD`)) {
        stopifnot(R6::is.R6(`AD`))
        self$`AD` <- `AD`
      }
      if (!missing(`AH`)) {
        stopifnot(R6::is.R6(`AH`))
        self$`AH` <- `AH`
      }
      if (!missing(`AM`)) {
        stopifnot(R6::is.R6(`AM`))
        self$`AM` <- `AM`
      }
      if (!missing(`AW`)) {
        stopifnot(R6::is.R6(`AW`))
        self$`AW` <- `AW`
      }
      if (!missing(`ID`)) {
        stopifnot(R6::is.R6(`ID`))
        self$`ID` <- `ID`
      }
    },
    toJSON = function() {
      PostStreamResponseObject <- list()
      if (!is.null(self$`state`)) {
        PostStreamResponseObject[['state']] <- self$`state`
      }
      if (!is.null(self$`message`)) {
        PostStreamResponseObject[['message']] <- self$`message`
      }
      if (!is.null(self$`progress`)) {
        PostStreamResponseObject[['progress']] <- self$`progress`
      }
      if (!is.null(self$`clusterCount`)) {
        PostStreamResponseObject[['clusterCount']] <- self$`clusterCount`
      }
      if (!is.null(self$`retryCount`)) {
        PostStreamResponseObject[['retryCount']] <- self$`retryCount`
      }
      if (!is.null(self$`streamingWindowSize`)) {
        PostStreamResponseObject[['streamingWindowSize']] <- self$`streamingWindowSize`
      }
      if (!is.null(self$`totalInferences`)) {
        PostStreamResponseObject[['totalInferences']] <- self$`totalInferences`
      }
      if (!is.null(self$`RI`)) {
        PostStreamResponseObject[['RI']] <- self$`RI`
      }
      if (!is.null(self$`SI`)) {
        PostStreamResponseObject[['SI']] <- self$`SI`
      }
      if (!is.null(self$`AD`)) {
        PostStreamResponseObject[['AD']] <- self$`AD`
      }
      if (!is.null(self$`AH`)) {
        PostStreamResponseObject[['AH']] <- self$`AH`
      }
      if (!is.null(self$`AM`)) {
        PostStreamResponseObject[['AM']] <- self$`AM`
      }
      if (!is.null(self$`AW`)) {
        PostStreamResponseObject[['AW']] <- self$`AW`
      }
      if (!is.null(self$`ID`)) {
        PostStreamResponseObject[['ID']] <- self$`ID`
      }

      PostStreamResponseObject
    },
    fromJSON = function(PostStreamResponseJson) {
      PostStreamResponseObject <- jsonlite::fromJSON(PostStreamResponseJson, simplifyVector = FALSE)
      if (!is.null(PostStreamResponseObject$`state`)) {
        self$`state` <- PostStreamResponseObject$`state`
      }
      if (!is.null(PostStreamResponseObject$`message`)) {
        self$`message` <- PostStreamResponseObject$`message`
      }
      if (!is.null(PostStreamResponseObject$`progress`)) {
        self$`progress` <- PostStreamResponseObject$progress
      }
      if (!is.null(PostStreamResponseObject$`clusterCount`)) {
        self$`clusterCount` <- PostStreamResponseObject$clusterCount
      }
      if (!is.null(PostStreamResponseObject$`retryCount`)) {
        self$`retryCount` <- PostStreamResponseObject$retryCount
      }
      if (!is.null(PostStreamResponseObject$`streamingWindowSize`)) {
        self$`streamingWindowSize` <- PostStreamResponseObject$streamingWindowSize
      }
      if (!is.null(PostStreamResponseObject$`totalInferences`)) {
        self$`totalInferences` <- PostStreamResponseObject$totalInferences
      }
      if (!is.null(PostStreamResponseObject$`RI`)) {
        self$`RI` <- PostStreamResponseObject$RI
      }
      if (!is.null(PostStreamResponseObject$`SI`)) {
        self$`SI` <- PostStreamResponseObject$SI
      }
      if (!is.null(PostStreamResponseObject$`AD`)) {
        self$`AD` <- PostStreamResponseObject$AD
      }
      if (!is.null(PostStreamResponseObject$`AH`)) {
        self$`AH` <- PostStreamResponseObject$AH
      }
      if (!is.null(PostStreamResponseObject$`AM`)) {
        self$`AM` <- PostStreamResponseObject$AM
      }
      if (!is.null(PostStreamResponseObject$`AW`)) {
        self$`AW` <- PostStreamResponseObject$AW
      }
      if (!is.null(PostStreamResponseObject$`ID`)) {
        self$`ID` <- PostStreamResponseObject$ID
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "state": %s,
           "message": %s,
           "progress": %s,
           "clusterCount": %s,
           "retryCount": %s,
           "streamingWindowSize": %s,
           "totalInferences": %s,
           "RI": %s,
           "SI": %s,
           "AD": %s,
           "AH": %s,
           "AM": %s,
           "AW": %s,
           "ID": %s
        }',
        self$`state`,
        self$`message`,
        self$`progress`,
        self$`clusterCount`,
        self$`retryCount`,
        self$`streamingWindowSize`,
        self$`totalInferences`,
        self$`RI`,
        self$`SI`,
        self$`AD`,
        self$`AH`,
        self$`AM`,
        self$`AW`,
        self$`ID`
      )
    },
    fromJSONString = function(PostStreamResponseJson) {
      PostStreamResponseObject <- jsonlite::fromJSON(PostStreamResponseJson, simplifyVector = FALSE)
      self$`state` <- PostStreamResponseObject$`state`
      self$`message` <- PostStreamResponseObject$`message`
      self$`progress` <- PostStreamResponseObject$progress
      self$`clusterCount` <- PostStreamResponseObject$clusterCount
      self$`retryCount` <- PostStreamResponseObject$retryCount
      self$`streamingWindowSize` <- PostStreamResponseObject$streamingWindowSize
      self$`totalInferences` <- PostStreamResponseObject$totalInferences
      self$`RI` <- PostStreamResponseObject$RI
      self$`SI` <- PostStreamResponseObject$SI
      self$`AD` <- PostStreamResponseObject$AD
      self$`AH` <- PostStreamResponseObject$AH
      self$`AM` <- PostStreamResponseObject$AM
      self$`AW` <- PostStreamResponseObject$AW
      self$`ID` <- PostStreamResponseObject$ID
    }
  )
)

