# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PostConfigResponse Class
#'
#' @field anomalyHistoryWindow 
#' @field learningRateNumerator 
#' @field learningRateDenominator 
#' @field learningMaxClusters 
#' @field learningMaxSamples 
#' @field featureCount 
#' @field streamingWindowSize 
#' @field features 
#' @field samplesToBuffer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PostConfigResponse <- R6::R6Class(
  'PostConfigResponse',
  public = list(
    `anomalyHistoryWindow` = NULL,
    `learningRateNumerator` = NULL,
    `learningRateDenominator` = NULL,
    `learningMaxClusters` = NULL,
    `learningMaxSamples` = NULL,
    `featureCount` = NULL,
    `streamingWindowSize` = NULL,
    `features` = NULL,
    `samplesToBuffer` = NULL,
    initialize = function(`anomalyHistoryWindow`, `learningRateNumerator`, `learningRateDenominator`, `learningMaxClusters`, `learningMaxSamples`, `featureCount`, `streamingWindowSize`, `features`, `samplesToBuffer`){
      if (!missing(`anomalyHistoryWindow`)) {
        stopifnot(is.numeric(`anomalyHistoryWindow`), length(`anomalyHistoryWindow`) == 1)
        stopifnot(R6::is.R6(`anomalyHistoryWindow`))
        self$`anomalyHistoryWindow` <- `anomalyHistoryWindow`
      }
      if (!missing(`learningRateNumerator`)) {
        stopifnot(is.numeric(`learningRateNumerator`), length(`learningRateNumerator`) == 1)
        stopifnot(R6::is.R6(`learningRateNumerator`))
        self$`learningRateNumerator` <- `learningRateNumerator`
      }
      if (!missing(`learningRateDenominator`)) {
        stopifnot(is.numeric(`learningRateDenominator`), length(`learningRateDenominator`) == 1)
        stopifnot(R6::is.R6(`learningRateDenominator`))
        self$`learningRateDenominator` <- `learningRateDenominator`
      }
      if (!missing(`learningMaxClusters`)) {
        stopifnot(is.numeric(`learningMaxClusters`), length(`learningMaxClusters`) == 1)
        stopifnot(R6::is.R6(`learningMaxClusters`))
        self$`learningMaxClusters` <- `learningMaxClusters`
      }
      if (!missing(`learningMaxSamples`)) {
        stopifnot(is.numeric(`learningMaxSamples`), length(`learningMaxSamples`) == 1)
        stopifnot(R6::is.R6(`learningMaxSamples`))
        self$`learningMaxSamples` <- `learningMaxSamples`
      }
      if (!missing(`featureCount`)) {
        stopifnot(is.numeric(`featureCount`), length(`featureCount`) == 1)
        self$`featureCount` <- `featureCount`
      }
      if (!missing(`streamingWindowSize`)) {
        stopifnot(is.numeric(`streamingWindowSize`), length(`streamingWindowSize`) == 1)
        self$`streamingWindowSize` <- `streamingWindowSize`
      }
      if (!missing(`features`)) {
        stopifnot(is.list(`features`), length(`features`) != 0)
        lapply(`features`, function(x) stopifnot(R6::is.R6(x)))
        self$`features` <- `features`
      }
      if (!missing(`samplesToBuffer`)) {
        stopifnot(is.numeric(`samplesToBuffer`), length(`samplesToBuffer`) == 1)
        stopifnot(R6::is.R6(`samplesToBuffer`))
        self$`samplesToBuffer` <- `samplesToBuffer`
      }
    },
    toJSON = function() {
      PostConfigResponseObject <- list()
      if (!is.null(self$`anomalyHistoryWindow`)) {
        PostConfigResponseObject[['anomalyHistoryWindow']] <- self$`anomalyHistoryWindow`
      }
      if (!is.null(self$`learningRateNumerator`)) {
        PostConfigResponseObject[['learningRateNumerator']] <- self$`learningRateNumerator`
      }
      if (!is.null(self$`learningRateDenominator`)) {
        PostConfigResponseObject[['learningRateDenominator']] <- self$`learningRateDenominator`
      }
      if (!is.null(self$`learningMaxClusters`)) {
        PostConfigResponseObject[['learningMaxClusters']] <- self$`learningMaxClusters`
      }
      if (!is.null(self$`learningMaxSamples`)) {
        PostConfigResponseObject[['learningMaxSamples']] <- self$`learningMaxSamples`
      }
      if (!is.null(self$`featureCount`)) {
        PostConfigResponseObject[['featureCount']] <- self$`featureCount`
      }
      if (!is.null(self$`streamingWindowSize`)) {
        PostConfigResponseObject[['streamingWindowSize']] <- self$`streamingWindowSize`
      }
      if (!is.null(self$`features`)) {
        PostConfigResponseObject[['features']] <- lapply(self$`features`, function(x) x$toJSON())
      }
      if (!is.null(self$`samplesToBuffer`)) {
        PostConfigResponseObject[['samplesToBuffer']] <- self$`samplesToBuffer`
      }

      PostConfigResponseObject
    },
    fromJSON = function(PostConfigResponseJson) {
      PostConfigResponseObject <- jsonlite::fromJSON(PostConfigResponseJson, simplifyVector = FALSE)
      if (!is.null(PostConfigResponseObject$`anomalyHistoryWindow`)) {
        self$`anomalyHistoryWindow` <- PostConfigResponseObject$anomalyHistoryWindow
      }
      if (!is.null(PostConfigResponseObject$`learningRateNumerator`)) {
        self$`learningRateNumerator` <- PostConfigResponseObject$learningRateNumerator
      }
      if (!is.null(PostConfigResponseObject$`learningRateDenominator`)) {
        self$`learningRateDenominator` <- PostConfigResponseObject$learningRateDenominator
      }
      if (!is.null(PostConfigResponseObject$`learningMaxClusters`)) {
        self$`learningMaxClusters` <- PostConfigResponseObject$learningMaxClusters
      }
      if (!is.null(PostConfigResponseObject$`learningMaxSamples`)) {
        self$`learningMaxSamples` <- PostConfigResponseObject$learningMaxSamples
      }
      if (!is.null(PostConfigResponseObject$`featureCount`)) {
        self$`featureCount` <- PostConfigResponseObject$`featureCount`
      }
      if (!is.null(PostConfigResponseObject$`streamingWindowSize`)) {
        self$`streamingWindowSize` <- PostConfigResponseObject$`streamingWindowSize`
      }
      if (!is.null(PostConfigResponseObject$`features`)) {
        self$`features` <- lapply(PostConfigResponseObject$`features`, function(x) {
          featuresObject <- FeatureConfig$new()
          featuresObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          featuresObject
        })
      }
      if (!is.null(PostConfigResponseObject$`samplesToBuffer`)) {
        self$`samplesToBuffer` <- PostConfigResponseObject$samplesToBuffer
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "anomalyHistoryWindow": %s,
           "learningRateNumerator": %s,
           "learningRateDenominator": %s,
           "learningMaxClusters": %s,
           "learningMaxSamples": %s,
           "featureCount": %d,
           "streamingWindowSize": %d,
           "features": [%s],
           "samplesToBuffer": %s
        }',
        self$`anomalyHistoryWindow`,
        self$`learningRateNumerator`,
        self$`learningRateDenominator`,
        self$`learningMaxClusters`,
        self$`learningMaxSamples`,
        self$`featureCount`,
        self$`streamingWindowSize`,
        lapply(self$`features`, function(x) paste(x$toJSON(), sep=",")),
        self$`samplesToBuffer`
      )
    },
    fromJSONString = function(PostConfigResponseJson) {
      PostConfigResponseObject <- jsonlite::fromJSON(PostConfigResponseJson, simplifyVector = FALSE)
      self$`anomalyHistoryWindow` <- PostConfigResponseObject$anomalyHistoryWindow
      self$`learningRateNumerator` <- PostConfigResponseObject$learningRateNumerator
      self$`learningRateDenominator` <- PostConfigResponseObject$learningRateDenominator
      self$`learningMaxClusters` <- PostConfigResponseObject$learningMaxClusters
      self$`learningMaxSamples` <- PostConfigResponseObject$learningMaxSamples
      self$`featureCount` <- PostConfigResponseObject$`featureCount`
      self$`streamingWindowSize` <- PostConfigResponseObject$`streamingWindowSize`
      self$`features` <- lapply(PostConfigResponseObject$`features`, function(x) FeatureConfig$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`samplesToBuffer` <- PostConfigResponseObject$samplesToBuffer
    }
  )
)

