# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PostOutageResponse Class
#'
#' @field state 
#' @field message 
#' @field progress 
#' @field clusterCount 
#' @field retryCount 
#' @field streamingWindowSize 
#' @field totalInferences 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PostOutageResponse <- R6::R6Class(
  'PostOutageResponse',
  public = list(
    `state` = NULL,
    `message` = NULL,
    `progress` = NULL,
    `clusterCount` = NULL,
    `retryCount` = NULL,
    `streamingWindowSize` = NULL,
    `totalInferences` = NULL,
    initialize = function(`state`, `message`, `progress`, `clusterCount`, `retryCount`, `streamingWindowSize`, `totalInferences`){
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`progress`)) {
        stopifnot(is.numeric(`progress`), length(`progress`) == 1)
        stopifnot(R6::is.R6(`progress`))
        self$`progress` <- `progress`
      }
      if (!missing(`clusterCount`)) {
        stopifnot(is.numeric(`clusterCount`), length(`clusterCount`) == 1)
        stopifnot(R6::is.R6(`clusterCount`))
        self$`clusterCount` <- `clusterCount`
      }
      if (!missing(`retryCount`)) {
        stopifnot(is.numeric(`retryCount`), length(`retryCount`) == 1)
        stopifnot(R6::is.R6(`retryCount`))
        self$`retryCount` <- `retryCount`
      }
      if (!missing(`streamingWindowSize`)) {
        stopifnot(is.numeric(`streamingWindowSize`), length(`streamingWindowSize`) == 1)
        stopifnot(R6::is.R6(`streamingWindowSize`))
        self$`streamingWindowSize` <- `streamingWindowSize`
      }
      if (!missing(`totalInferences`)) {
        stopifnot(is.numeric(`totalInferences`), length(`totalInferences`) == 1)
        stopifnot(R6::is.R6(`totalInferences`))
        self$`totalInferences` <- `totalInferences`
      }
    },
    toJSON = function() {
      PostOutageResponseObject <- list()
      if (!is.null(self$`state`)) {
        PostOutageResponseObject[['state']] <- self$`state`
      }
      if (!is.null(self$`message`)) {
        PostOutageResponseObject[['message']] <- self$`message`
      }
      if (!is.null(self$`progress`)) {
        PostOutageResponseObject[['progress']] <- self$`progress`
      }
      if (!is.null(self$`clusterCount`)) {
        PostOutageResponseObject[['clusterCount']] <- self$`clusterCount`
      }
      if (!is.null(self$`retryCount`)) {
        PostOutageResponseObject[['retryCount']] <- self$`retryCount`
      }
      if (!is.null(self$`streamingWindowSize`)) {
        PostOutageResponseObject[['streamingWindowSize']] <- self$`streamingWindowSize`
      }
      if (!is.null(self$`totalInferences`)) {
        PostOutageResponseObject[['totalInferences']] <- self$`totalInferences`
      }

      PostOutageResponseObject
    },
    fromJSON = function(PostOutageResponseJson) {
      PostOutageResponseObject <- jsonlite::fromJSON(PostOutageResponseJson, simplifyVector = FALSE)
      if (!is.null(PostOutageResponseObject$`state`)) {
        self$`state` <- PostOutageResponseObject$`state`
      }
      if (!is.null(PostOutageResponseObject$`message`)) {
        self$`message` <- PostOutageResponseObject$`message`
      }
      if (!is.null(PostOutageResponseObject$`progress`)) {
        self$`progress` <- PostOutageResponseObject$progress
      }
      if (!is.null(PostOutageResponseObject$`clusterCount`)) {
        self$`clusterCount` <- PostOutageResponseObject$clusterCount
      }
      if (!is.null(PostOutageResponseObject$`retryCount`)) {
        self$`retryCount` <- PostOutageResponseObject$retryCount
      }
      if (!is.null(PostOutageResponseObject$`streamingWindowSize`)) {
        self$`streamingWindowSize` <- PostOutageResponseObject$streamingWindowSize
      }
      if (!is.null(PostOutageResponseObject$`totalInferences`)) {
        self$`totalInferences` <- PostOutageResponseObject$totalInferences
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "state": %s,
           "message": %s,
           "progress": %s,
           "clusterCount": %s,
           "retryCount": %s,
           "streamingWindowSize": %s,
           "totalInferences": %s
        }',
        self$`state`,
        self$`message`,
        self$`progress`,
        self$`clusterCount`,
        self$`retryCount`,
        self$`streamingWindowSize`,
        self$`totalInferences`
      )
    },
    fromJSONString = function(PostOutageResponseJson) {
      PostOutageResponseObject <- jsonlite::fromJSON(PostOutageResponseJson, simplifyVector = FALSE)
      self$`state` <- PostOutageResponseObject$`state`
      self$`message` <- PostOutageResponseObject$`message`
      self$`progress` <- PostOutageResponseObject$progress
      self$`clusterCount` <- PostOutageResponseObject$clusterCount
      self$`retryCount` <- PostOutageResponseObject$retryCount
      self$`streamingWindowSize` <- PostOutageResponseObject$streamingWindowSize
      self$`totalInferences` <- PostOutageResponseObject$totalInferences
    }
  )
)

