# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PutConfigResponse Class
#'
#' @field features 
#' @field streaming 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PutConfigResponse <- R6::R6Class(
  'PutConfigResponse',
  public = list(
    `features` = NULL,
    `streaming` = NULL,
    initialize = function(`features`, `streaming`){
      if (!missing(`features`)) {
        stopifnot(is.list(`features`), length(`features`) != 0)
        lapply(`features`, function(x) stopifnot(R6::is.R6(x)))
        self$`features` <- `features`
      }
      if (!missing(`streaming`)) {
        stopifnot(R6::is.R6(`streaming`))
        self$`streaming` <- `streaming`
      }
    },
    toJSON = function() {
      PutConfigResponseObject <- list()
      if (!is.null(self$`features`)) {
        PutConfigResponseObject[['features']] <- lapply(self$`features`, function(x) x$toJSON())
      }
      if (!is.null(self$`streaming`)) {
        PutConfigResponseObject[['streaming']] <- self$`streaming`$toJSON()
      }

      PutConfigResponseObject
    },
    fromJSON = function(PutConfigResponseJson) {
      PutConfigResponseObject <- jsonlite::fromJSON(PutConfigResponseJson)
      if (!is.null(PutConfigResponseObject$`features`)) {
        self$`features` <- lapply(PutConfigResponseObject$`features`, function(x) {
          featuresObject <- FusionConfig$new()
          featuresObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          featuresObject
        })
      }
      if (!is.null(PutConfigResponseObject$`streaming`)) {
        streamingObject <- StreamingParameters$new()
        streamingObject$fromJSON(jsonlite::toJSON(PutConfigResponseObject$streaming, auto_unbox = TRUE))
        self$`streaming` <- streamingObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "features": [%s],
           "streaming": %s
        }',
        lapply(self$`features`, function(x) paste(x$toJSON(), sep=",")),
        self$`streaming`$toJSON()
      )
    },
    fromJSONString = function(PutConfigResponseJson) {
      PutConfigResponseObject <- jsonlite::fromJSON(PutConfigResponseJson)
      self$`features` <- lapply(PutConfigResponseObject$`features`, function(x) FusionConfig$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      StreamingParametersObject <- StreamingParameters$new()
      self$`streaming` <- StreamingParametersObject$fromJSON(jsonlite::toJSON(PutConfigResponseObject$streaming, auto_unbox = TRUE))
    }
  )
)
