# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PutStreamResponse Class
#'
#' @field vector 
#' @field results 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PutStreamResponse <- R6::R6Class(
  'PutStreamResponse',
  public = list(
    `vector` = NULL,
    `results` = NULL,
    initialize = function(`vector`, `results`){
      if (!missing(`vector`)) {
        stopifnot(is.character(`vector`), length(`vector`) == 1)
        self$`vector` <- `vector`
      }
      if (!missing(`results`)) {
        stopifnot(R6::is.R6(`results`))
        self$`results` <- `results`
      }
    },
    toJSON = function() {
      PutStreamResponseObject <- list()
      if (!is.null(self$`vector`)) {
        PutStreamResponseObject[['vector']] <- self$`vector`
      }
      if (!is.null(self$`results`)) {
        PutStreamResponseObject[['results']] <- self$`results`$toJSON()
      }

      PutStreamResponseObject
    },
    fromJSON = function(PutStreamResponseJson) {
      PutStreamResponseObject <- jsonlite::fromJSON(PutStreamResponseJson)
      if (!is.null(PutStreamResponseObject$`vector`)) {
        self$`vector` <- PutStreamResponseObject$`vector`
      }
      if (!is.null(PutStreamResponseObject$`results`)) {
        resultsObject <- PostStreamResponse$new()
        resultsObject$fromJSON(jsonlite::toJSON(PutStreamResponseObject$results, auto_unbox = TRUE))
        self$`results` <- resultsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "vector": %s,
           "results": %s
        }',
        self$`vector`,
        self$`results`$toJSON()
      )
    },
    fromJSONString = function(PutStreamResponseJson) {
      PutStreamResponseObject <- jsonlite::fromJSON(PutStreamResponseJson)
      self$`vector` <- PutStreamResponseObject$`vector`
      PostStreamResponseObject <- PostStreamResponse$new()
      self$`results` <- PostStreamResponseObject$fromJSON(jsonlite::toJSON(PutStreamResponseObject$results, auto_unbox = TRUE))
    }
  )
)
