# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PutSensorResponse Class
#'
#' @field label 
#' @field sensorId 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PutSensorResponse <- R6::R6Class("PutSensorResponse", public = list(label = NULL,
    sensorId = NULL, initialize = function(label, sensorId) {
        if (!missing(label)) {
            stopifnot(is.character(label), length(label) == 1)
            self$label <- label
        }
        if (!missing(sensorId)) {
            stopifnot(is.character(sensorId), length(sensorId) == 1)
            self$sensorId <- sensorId
        }
    }, toJSON = function() {
        PutSensorResponseObject <- list()
        if (!is.null(self$label)) {
            PutSensorResponseObject[["label"]] <- self$label
        }
        if (!is.null(self$sensorId)) {
            PutSensorResponseObject[["sensorId"]] <- self$sensorId
        }

        PutSensorResponseObject
    }, fromJSON = function(PutSensorResponseJson) {
        PutSensorResponseObject <- jsonlite::fromJSON(PutSensorResponseJson)
        if (!is.null(PutSensorResponseObject$label)) {
            self$label <- PutSensorResponseObject$label
        }
        if (!is.null(PutSensorResponseObject$sensorId)) {
            self$sensorId <- PutSensorResponseObject$sensorId
        }
    }, toJSONString = function() {
        sprintf("{
           \"label\": %s,
           \"sensorId\": %s
        }",
            self$label, self$sensorId)
    }, fromJSONString = function(PutSensorResponseJson) {
        PutSensorResponseObject <- jsonlite::fromJSON(PutSensorResponseJson)
        self$label <- PutSensorResponseObject$label
        self$sensorId <- PutSensorResponseObject$sensorId
    }))
