# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#' @title Default operations
#' @description swagger.Default
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' delete_sensor Delete a sensor instance
#'
#'
#' get_amber_summary Get the JSON block of the amber image
#'
#'
#' get_config Get the current configuration of a sensor instance
#'
#'
#' get_pretrain Get status of pretrain operation
#'
#'
#' get_root_cause Get root cause analysis information from a sensor
#'
#'
#' get_sensor Get basic information about a sensor instance
#'
#'
#' get_sensors List all sensors for this user
#'
#'
#' get_status Get analytic information from a sensor
#'
#'
#' get_version Retrieves API version information
#'
#'
#' post_config Apply configuration to a sensor instance
#'
#'
#' post_oauth2 Request a bearer token using Amber account credentials
#'
#'
#' post_pretrain Pretrain a sensor using historical data
#'
#'
#' post_sensor Create a new a sensor instance
#'
#'
#' post_stream Stream data to a sensor
#'
#'
#' put_config Update configuration for a sensor instance
#'
#'
#' put_sensor Update label for a sensor instance
#'
#'
#' put_stream Stream data to a sensor fusion vector
#'
#' }
#'
#' @export
DefaultApi <- R6::R6Class("DefaultApi", public = list(userAgent = "Boon Logic / amber-r-sdk / requests",
    apiClient = NULL, initialize = function(apiClient) {
        if (!missing(apiClient)) {
            self$apiClient <- apiClient
        } else {
            self$apiClient <- ApiClient$new()
        }
    }, list_sensors = function(...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        urlPath <- "/sensors"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetSensorsResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_sensor = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/sensor"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetSensorResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, create_sensor = function(body, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/sensor"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostSensorResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, update_label = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/sensor"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "PUT", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PutSensorResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, configure_sensor = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/config"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostConfigResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, configure_fusion = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/config"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "PUT", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PutConfigResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, enable_learning = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/config"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "PUT", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PutConfigResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_config = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/config"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetConfigResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, delete_sensor = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/sensor"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "DELETE", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- Error$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, stream_sensor = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/stream"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostStreamResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, stream_fusion = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/stream"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "PUT", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PutStreamResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_status = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/status"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetStatusResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, pretrain_sensor = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/pretrain"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostPretrainResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_pretrain_state = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/pretrain"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetPretrainResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_root_cause = function(sensor_id, cluster_id, pattern, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(cluster_id)) {
            queryParams["clusterID"] <- cluster_id
        }

        if (!missing(pattern)) {
            queryParams["pattern"] <- pattern
        }

        urlPath <- "/rootCause"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetRootCauseResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_version = function(...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        urlPath <- "/version"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- Version$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, post_oauth2 = function(body, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/oauth2"
        resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostAuth2Response$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }))
