# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#' @title Default operations
#' @description swagger.Default
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' delete_sensor Delete a sensor instance
#'
#'
#' get_amber_summary Get the JSON block of the amber image
#'
#'
#' get_config Get the current configuration of a sensor instance
#'
#'
#' get_pretrain_state Get status of pretrain operation
#'
#'
#' get_root_cause Get root cause analysis information from a sensor
#'
#'
#' get_sensor Get basic information about a sensor instance
#'
#'
#' list_sensors List all sensors for this user
#'
#'
#' get_status Get analytic information from a sensor
#'
#'
#' get_version Retrieves API version information
#'
#'
#' configure_sensor Apply configuration to a sensor instance
#'
#'
#' post_oauth2 Request a bearer token using Amber account credentials
#'
#'
#' pretrain_sensor Pretrain a sensor using historical data
#'
#'
#' create_sensor Create a new a sensor instance
#'
#'
#' stream_sensor Stream data to a sensor
#'
#'
#' configure_fusion Update configuration for a sensor instance for fusion data
#'
#'
#' enable_learning set new graduation requirements and turns on learning
#'
#'
#' update_label Update label for a sensor instance
#'
#'
#' stream_fusion Stream data to a sensor fusion vector
#'
#' }
#'
#' @export
AmberClient <- R6::R6Class(
  "AmberClient", 
  private = list(
    userAgent = "Boon Logic / amber-r-sdk / requests",
    verify = TRUE,
    cert = NULL,
    timeout = 360,
    token = NULL,
    reauth_time = 0,
    license_profile =  NULL,
    authenticate = function(...) {
      # TODO: get time in
      tIn = Sys.time()
      if (reauth_time %<% tIn) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        urlPath <- "/oauth2"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["oauth-server"]], urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostSensorResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }
      }
      c(TRUE, NULL)

    }
  ),
  public = list(
    license_id = NULL,
    license_file = NULL,
    initialize = function(license_id = "default", license_file = "~/.Amber.license", verify = TRUE, cert = NULL, timeout = 360) {
        
        self$license_file <- license_file
        self$license_file <- Sys.getenv("AMBER_LICENSE_FILE", unset = self$license_file)

        self$license_id <- license_id
        self$license_id <- Sys.getenv("AMBER_LICENSE_ID", unset = self$license_id)

        if (!is.null(license_file)) {
          license_path <- path_real(self$license_file)
          if (file.exists(license_path)){
            file_data = NULL
            tryCatch(
              file_data <- rjson::fromJSON(file = license_path),
              error = function(c) {
                msg = paste(cat("JSON formatting error in license file: ", license_path))
                rlang::abort(msg, class = "AmberUserError")
              }
            )

            trycatch(
              self$license_profile <- file_data[[self$license_id]],
              error = function(c) {
                msg = paste(cat("license_id ", license_id, " not found in license file"))
                rlang::abort(msg, class = "AmberUserError")
              }
            )
          } else {
            self$license_path <- rjson::fromJSON('{"username": "", "password": "", "server": "", "oauth-server": ""}')
          }
        } else {
          self$license_path <- rjson::fromJSON('{"username": "", "password": "", "server": "", "oauth-server": ""}')
        }

        tryCatch(
          {
            self$license_profile[["username"]] <- Sys.getenv("AMBER_USERNAME", self$license_profile[["username"]])
            self$license_profile[["password"]] <- Sys.getenv("AMBER_PASSWORD", self$license_profile[["password"]])
            self$license_profile[["server"]] <- Sys.getenv("AMBER_SERVER", self$license_profile[["server"]])
            # TODO: check if key is missing in license profile oauth-server
            if (missing(self$license_profile[["oauth-server"]] || is.null(self$license_profile))) {
              self$license_profile[["oauth-server"]] <- self$license_profile[["server"]]
            }
            self$license_profile[["oauth-server"]] <- Sys.getenv("AMBER_OAUTH_SERVER", self$license_profile[["oauth-server"]])

            self$license_profile[["cert"]] <- Sys.getenv("AMBER_SSL_CERT", cert)
            verify_str = toLower(Sys.getenv("AMBER_SSL_VERIFY", "true"))
            self$license_profile[["verify"]] <- TRUE # Default
            if (!verify || verify_str == "false") {
              self$license_profile[["verify"]] <- FALSE
            }
          },

          error = function(c) {
            msg = paste("missing field")
            rlang::abort(msg, class = "AmberUserError")
          }
        )

        if (!self$license_profile[["verify"]]) {
          # TODO: set verify to false in request thing
          print("do something!")
        }

        if (self$license_profile[["username"]] == ""){
          msg = paste("username not found in specified")
          rlang::abort(msg, class = "AmberUserError")
        }
        if (self$license_profile[["password"]] == ""){
          msg = paste("password not found in specified")
          rlang::abort(msg, class = "AmberUserError")
        }
        if (self$license_profile[["server"]] == ""){
          msg = paste("server not found in specified")
          rlang::abort(msg, class = "AmberUserError")
        }

    }, list_sensors = function(...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        urlPath <- "/sensors"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetSensorsResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_sensor = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/sensor"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetSensorResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, create_sensor = function(body, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/sensor"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostSensorResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, update_label = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/sensor"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "PUT", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PutSensorResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, configure_sensor = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/config"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostConfigResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, configure_fusion = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/config"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "PUT", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PutConfigResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, enable_learning = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/config"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "PUT", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PutConfigResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_config = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/config"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetConfigResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, delete_sensor = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/sensor"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "DELETE", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- Error$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, stream_sensor = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/stream"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostStreamResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, stream_fusion = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/stream"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "PUT", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PutStreamResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_status = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/status"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetStatusResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, pretrain_sensor = function(body, sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/pretrain"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostPretrainResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_pretrain_state = function(sensor_id, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        urlPath <- "/pretrain"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetPretrainResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_root_cause = function(sensor_id, cluster_id, pattern, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(sensor_id)) {
            headerParams["sensorId"] <- sensor_id
        }

        if (!missing(cluster_id)) {
            queryParams["clusterID"] <- cluster_id
        }

        if (!missing(pattern)) {
            queryParams["pattern"] <- pattern
        }

        urlPath <- "/rootCause"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- GetRootCauseResponse$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, get_version = function(...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        urlPath <- "/version"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "GET", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- Version$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, post_oauth2 = function(body, ...) {
        args <- list(...)
        queryParams <- list()
        headerParams <- character()

        if (!missing(body)) {
            body <- body$toJSONString()
        } else {
            body <- NULL
        }

        urlPath <- "/oauth2"
        resp <- self$apiClient$callApi(url = paste0(self$license_profile[["server"]], urlPath),
            method = "POST", queryParams = queryParams, headerParams = headerParams,
            body = body, ...)

        if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
            returnObject <- PostAuth2Response$new()
            result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
            Response$new(returnObject, resp)
        } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
            Response$new("API client error", resp)
        } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
            Response$new("API server error", resp)
        }

    }, callApi = function(url, method, queryParams, headerParams, body, ...){
        headers <- httr::add_headers(headerParams)

        if (method == "GET") {
            httr::GET(url, queryParams, headers, ...)
        }
        else if (method == "POST") {
            httr::POST(url, queryParams, headers, body = body, ...)
        }
        else if (method == "PUT") {
            httr::PUT(url, queryParams, headers, body = body, ...)
        }
        else if (method == "PATCH") {
            httr::PATCH(url, queryParams, headers, body = body, ...)
        }
        else if (method == "HEAD") {
            httr::HEAD(url, queryParams, headers, ...)
        }
        else if (method == "DELETE") {
            httr::DELETE(url, queryParams, headers, ...)
        }
        else {
            stop("http method must be `GET`, `HEAD`, `OPTIONS`, `POST`, `PATCH`, `PUT` or `DELETE`.")
        }
    }
  )
)
