# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' SensorInstance Class
#'
#' @field label 
#' @field sensorId 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SensorInstance <- R6::R6Class("SensorInstance", public = list(label = NULL, sensorId = NULL,
    initialize = function(label, sensorId) {
        if (!missing(label)) {
            stopifnot(is.character(label), length(label) == 1)
            self$label <- label
        }
        if (!missing(sensorId)) {
            stopifnot(is.character(sensorId), length(sensorId) == 1)
            self$sensorId <- sensorId
        }
    }, toJSON = function() {
        SensorInstanceObject <- list()
        if (!is.null(self$label)) {
            SensorInstanceObject[["label"]] <- self$label
        }
        if (!is.null(self$sensorId)) {
            SensorInstanceObject[["sensorId"]] <- self$sensorId
        }

        SensorInstanceObject
    }, fromJSON = function(SensorInstanceJson) {
        SensorInstanceObject <- jsonlite::fromJSON(SensorInstanceJson)
        if (!is.null(SensorInstanceObject$label)) {
            self$label <- SensorInstanceObject$label
        }
        if (!is.null(SensorInstanceObject$sensorId)) {
            self$sensorId <- SensorInstanceObject$sensorId
        }
    }, toJSONString = function() {
        sprintf("{
           \"label\": %s,
           \"sensorId\": %s
        }",
            self$label, self$sensorId)
    }, fromJSONString = function(SensorInstanceJson) {
        SensorInstanceObject <- jsonlite::fromJSON(SensorInstanceJson)
        self$label <- SensorInstanceObject$label
        self$sensorId <- SensorInstanceObject$sensorId
    }))
