# Amber API Server Boon Logic Amber API Server OpenAPI spec version: 1.0.3
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' SensorUsageInfo Class
#'
#' @field postConfig 
#' @field postStream 
#' @field putSensor 
#' @field getSensor 
#' @field getConfig 
#' @field getStatus 
#' @field getRootCause 
#' @field getAmberSummary 
#' @field postPretrain 
#' @field getPretrain 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SensorUsageInfo <- R6::R6Class("SensorUsageInfo", public = list(postConfig = NULL,
    postStream = NULL, putSensor = NULL, getSensor = NULL, getConfig = NULL, getStatus = NULL,
    getRootCause = NULL, getAmberSummary = NULL, postPretrain = NULL, getPretrain = NULL,
    initialize = function(postConfig, postStream, putSensor, getSensor, getConfig,
        getStatus, getRootCause, getAmberSummary, postPretrain, getPretrain) {
        if (!missing(postConfig)) {
            stopifnot(R6::is.R6(postConfig))
            self$postConfig <- postConfig
        }
        if (!missing(postStream)) {
            stopifnot(R6::is.R6(postStream))
            self$postStream <- postStream
        }
        if (!missing(putSensor)) {
            stopifnot(R6::is.R6(putSensor))
            self$putSensor <- putSensor
        }
        if (!missing(getSensor)) {
            stopifnot(R6::is.R6(getSensor))
            self$getSensor <- getSensor
        }
        if (!missing(getConfig)) {
            stopifnot(R6::is.R6(getConfig))
            self$getConfig <- getConfig
        }
        if (!missing(getStatus)) {
            stopifnot(R6::is.R6(getStatus))
            self$getStatus <- getStatus
        }
        if (!missing(getRootCause)) {
            stopifnot(R6::is.R6(getRootCause))
            self$getRootCause <- getRootCause
        }
        if (!missing(getAmberSummary)) {
            stopifnot(R6::is.R6(getAmberSummary))
            self$getAmberSummary <- getAmberSummary
        }
        if (!missing(postPretrain)) {
            stopifnot(R6::is.R6(postPretrain))
            self$postPretrain <- postPretrain
        }
        if (!missing(getPretrain)) {
            stopifnot(R6::is.R6(getPretrain))
            self$getPretrain <- getPretrain
        }
    }, toJSON = function() {
        SensorUsageInfoObject <- list()
        if (!is.null(self$postConfig)) {
            SensorUsageInfoObject[["postConfig"]] <- self$postConfig$toJSON()
        }
        if (!is.null(self$postStream)) {
            SensorUsageInfoObject[["postStream"]] <- self$postStream$toJSON()
        }
        if (!is.null(self$putSensor)) {
            SensorUsageInfoObject[["putSensor"]] <- self$putSensor$toJSON()
        }
        if (!is.null(self$getSensor)) {
            SensorUsageInfoObject[["getSensor"]] <- self$getSensor$toJSON()
        }
        if (!is.null(self$getConfig)) {
            SensorUsageInfoObject[["getConfig"]] <- self$getConfig$toJSON()
        }
        if (!is.null(self$getStatus)) {
            SensorUsageInfoObject[["getStatus"]] <- self$getStatus$toJSON()
        }
        if (!is.null(self$getRootCause)) {
            SensorUsageInfoObject[["getRootCause"]] <- self$getRootCause$toJSON()
        }
        if (!is.null(self$getAmberSummary)) {
            SensorUsageInfoObject[["getAmberSummary"]] <- self$getAmberSummary$toJSON()
        }
        if (!is.null(self$postPretrain)) {
            SensorUsageInfoObject[["postPretrain"]] <- self$postPretrain$toJSON()
        }
        if (!is.null(self$getPretrain)) {
            SensorUsageInfoObject[["getPretrain"]] <- self$getPretrain$toJSON()
        }

        SensorUsageInfoObject
    }, fromJSON = function(SensorUsageInfoJson) {
        SensorUsageInfoObject <- jsonlite::fromJSON(SensorUsageInfoJson)
        if (!is.null(SensorUsageInfoObject$postConfig)) {
            postConfigObject <- EndpointUsageInfo$new()
            postConfigObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$postConfig,
                auto_unbox = TRUE))
            self$postConfig <- postConfigObject
        }
        if (!is.null(SensorUsageInfoObject$postStream)) {
            postStreamObject <- StreamingEndpointUsageInfo$new()
            postStreamObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$postStream,
                auto_unbox = TRUE))
            self$postStream <- postStreamObject
        }
        if (!is.null(SensorUsageInfoObject$putSensor)) {
            putSensorObject <- EndpointUsageInfo$new()
            putSensorObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$putSensor,
                auto_unbox = TRUE))
            self$putSensor <- putSensorObject
        }
        if (!is.null(SensorUsageInfoObject$getSensor)) {
            getSensorObject <- EndpointUsageInfo$new()
            getSensorObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getSensor,
                auto_unbox = TRUE))
            self$getSensor <- getSensorObject
        }
        if (!is.null(SensorUsageInfoObject$getConfig)) {
            getConfigObject <- EndpointUsageInfo$new()
            getConfigObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getConfig,
                auto_unbox = TRUE))
            self$getConfig <- getConfigObject
        }
        if (!is.null(SensorUsageInfoObject$getStatus)) {
            getStatusObject <- EndpointUsageInfo$new()
            getStatusObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getStatus,
                auto_unbox = TRUE))
            self$getStatus <- getStatusObject
        }
        if (!is.null(SensorUsageInfoObject$getRootCause)) {
            getRootCauseObject <- EndpointUsageInfo$new()
            getRootCauseObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getRootCause,
                auto_unbox = TRUE))
            self$getRootCause <- getRootCauseObject
        }
        if (!is.null(SensorUsageInfoObject$getAmberSummary)) {
            getAmberSummaryObject <- EndpointUsageInfo$new()
            getAmberSummaryObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getAmberSummary,
                auto_unbox = TRUE))
            self$getAmberSummary <- getAmberSummaryObject
        }
        if (!is.null(SensorUsageInfoObject$postPretrain)) {
            postPretrainObject <- EndpointUsageInfo$new()
            postPretrainObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$postPretrain,
                auto_unbox = TRUE))
            self$postPretrain <- postPretrainObject
        }
        if (!is.null(SensorUsageInfoObject$getPretrain)) {
            getPretrainObject <- EndpointUsageInfo$new()
            getPretrainObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getPretrain,
                auto_unbox = TRUE))
            self$getPretrain <- getPretrainObject
        }
    }, toJSONString = function() {
        sprintf("{
           \"postConfig\": %s,
           \"postStream\": %s,
           \"putSensor\": %s,
           \"getSensor\": %s,
           \"getConfig\": %s,
           \"getStatus\": %s,
           \"getRootCause\": %s,
           \"getAmberSummary\": %s,
           \"postPretrain\": %s,
           \"getPretrain\": %s
        }",
            self$postConfig$toJSON(), self$postStream$toJSON(), self$putSensor$toJSON(),
            self$getSensor$toJSON(), self$getConfig$toJSON(), self$getStatus$toJSON(),
            self$getRootCause$toJSON(), self$getAmberSummary$toJSON(), self$postPretrain$toJSON(),
            self$getPretrain$toJSON())
    }, fromJSONString = function(SensorUsageInfoJson) {
        SensorUsageInfoObject <- jsonlite::fromJSON(SensorUsageInfoJson)
        EndpointUsageInfoObject <- EndpointUsageInfo$new()
        self$postConfig <- EndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$postConfig,
            auto_unbox = TRUE))
        StreamingEndpointUsageInfoObject <- StreamingEndpointUsageInfo$new()
        self$postStream <- StreamingEndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$postStream,
            auto_unbox = TRUE))
        EndpointUsageInfoObject <- EndpointUsageInfo$new()
        self$putSensor <- EndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$putSensor,
            auto_unbox = TRUE))
        EndpointUsageInfoObject <- EndpointUsageInfo$new()
        self$getSensor <- EndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getSensor,
            auto_unbox = TRUE))
        EndpointUsageInfoObject <- EndpointUsageInfo$new()
        self$getConfig <- EndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getConfig,
            auto_unbox = TRUE))
        EndpointUsageInfoObject <- EndpointUsageInfo$new()
        self$getStatus <- EndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getStatus,
            auto_unbox = TRUE))
        EndpointUsageInfoObject <- EndpointUsageInfo$new()
        self$getRootCause <- EndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getRootCause,
            auto_unbox = TRUE))
        EndpointUsageInfoObject <- EndpointUsageInfo$new()
        self$getAmberSummary <- EndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getAmberSummary,
            auto_unbox = TRUE))
        EndpointUsageInfoObject <- EndpointUsageInfo$new()
        self$postPretrain <- EndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$postPretrain,
            auto_unbox = TRUE))
        EndpointUsageInfoObject <- EndpointUsageInfo$new()
        self$getPretrain <- EndpointUsageInfoObject$fromJSON(jsonlite::toJSON(SensorUsageInfoObject$getPretrain,
            auto_unbox = TRUE))
    }))
