# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' StreamStatus Class
#'
#' @field state 
#' @field message 
#' @field progress 
#' @field clusterCount 
#' @field retryCount 
#' @field streamingWindowSize 
#' @field totalInferences 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StreamStatus <- R6::R6Class(
  'StreamStatus',
  public = list(
    `state` = NULL,
    `message` = NULL,
    `progress` = NULL,
    `clusterCount` = NULL,
    `retryCount` = NULL,
    `streamingWindowSize` = NULL,
    `totalInferences` = NULL,
    initialize = function(`state`, `message`, `progress`, `clusterCount`, `retryCount`, `streamingWindowSize`, `totalInferences`){
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`progress`)) {
        stopifnot(is.numeric(`progress`), length(`progress`) == 1)
        stopifnot(R6::is.R6(`progress`))
        self$`progress` <- `progress`
      }
      if (!missing(`clusterCount`)) {
        stopifnot(is.numeric(`clusterCount`), length(`clusterCount`) == 1)
        stopifnot(R6::is.R6(`clusterCount`))
        self$`clusterCount` <- `clusterCount`
      }
      if (!missing(`retryCount`)) {
        stopifnot(is.numeric(`retryCount`), length(`retryCount`) == 1)
        stopifnot(R6::is.R6(`retryCount`))
        self$`retryCount` <- `retryCount`
      }
      if (!missing(`streamingWindowSize`)) {
        stopifnot(is.numeric(`streamingWindowSize`), length(`streamingWindowSize`) == 1)
        stopifnot(R6::is.R6(`streamingWindowSize`))
        self$`streamingWindowSize` <- `streamingWindowSize`
      }
      if (!missing(`totalInferences`)) {
        stopifnot(is.numeric(`totalInferences`), length(`totalInferences`) == 1)
        stopifnot(R6::is.R6(`totalInferences`))
        self$`totalInferences` <- `totalInferences`
      }
    },
    toJSON = function() {
      StreamStatusObject <- list()
      if (!is.null(self$`state`)) {
        StreamStatusObject[['state']] <- self$`state`
      }
      if (!is.null(self$`message`)) {
        StreamStatusObject[['message']] <- self$`message`
      }
      if (!is.null(self$`progress`)) {
        StreamStatusObject[['progress']] <- self$`progress`$toJSON()
      }
      if (!is.null(self$`clusterCount`)) {
        StreamStatusObject[['clusterCount']] <- self$`clusterCount`$toJSON()
      }
      if (!is.null(self$`retryCount`)) {
        StreamStatusObject[['retryCount']] <- self$`retryCount`$toJSON()
      }
      if (!is.null(self$`streamingWindowSize`)) {
        StreamStatusObject[['streamingWindowSize']] <- self$`streamingWindowSize`$toJSON()
      }
      if (!is.null(self$`totalInferences`)) {
        StreamStatusObject[['totalInferences']] <- self$`totalInferences`$toJSON()
      }

      StreamStatusObject
    },
    fromJSON = function(StreamStatusJson) {
      StreamStatusObject <- jsonlite::fromJSON(StreamStatusJson)
      if (!is.null(StreamStatusObject$`state`)) {
        self$`state` <- StreamStatusObject$`state`
      }
      if (!is.null(StreamStatusObject$`message`)) {
        self$`message` <- StreamStatusObject$`message`
      }
      if (!is.null(StreamStatusObject$`progress`)) {
        progressObject <- BigDecimal$new()
        progressObject$fromJSON(jsonlite::toJSON(StreamStatusObject$progress, auto_unbox = TRUE))
        self$`progress` <- progressObject
      }
      if (!is.null(StreamStatusObject$`clusterCount`)) {
        clusterCountObject <- BigDecimal$new()
        clusterCountObject$fromJSON(jsonlite::toJSON(StreamStatusObject$clusterCount, auto_unbox = TRUE))
        self$`clusterCount` <- clusterCountObject
      }
      if (!is.null(StreamStatusObject$`retryCount`)) {
        retryCountObject <- BigDecimal$new()
        retryCountObject$fromJSON(jsonlite::toJSON(StreamStatusObject$retryCount, auto_unbox = TRUE))
        self$`retryCount` <- retryCountObject
      }
      if (!is.null(StreamStatusObject$`streamingWindowSize`)) {
        streamingWindowSizeObject <- BigDecimal$new()
        streamingWindowSizeObject$fromJSON(jsonlite::toJSON(StreamStatusObject$streamingWindowSize, auto_unbox = TRUE))
        self$`streamingWindowSize` <- streamingWindowSizeObject
      }
      if (!is.null(StreamStatusObject$`totalInferences`)) {
        totalInferencesObject <- BigDecimal$new()
        totalInferencesObject$fromJSON(jsonlite::toJSON(StreamStatusObject$totalInferences, auto_unbox = TRUE))
        self$`totalInferences` <- totalInferencesObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "state": %s,
           "message": %s,
           "progress": %s,
           "clusterCount": %s,
           "retryCount": %s,
           "streamingWindowSize": %s,
           "totalInferences": %s
        }',
        self$`state`,
        self$`message`,
        self$`progress`$toJSON(),
        self$`clusterCount`$toJSON(),
        self$`retryCount`$toJSON(),
        self$`streamingWindowSize`$toJSON(),
        self$`totalInferences`$toJSON()
      )
    },
    fromJSONString = function(StreamStatusJson) {
      StreamStatusObject <- jsonlite::fromJSON(StreamStatusJson)
      self$`state` <- StreamStatusObject$`state`
      self$`message` <- StreamStatusObject$`message`
      BigDecimalObject <- BigDecimal$new()
      self$`progress` <- BigDecimalObject$fromJSON(jsonlite::toJSON(StreamStatusObject$progress, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`clusterCount` <- BigDecimalObject$fromJSON(jsonlite::toJSON(StreamStatusObject$clusterCount, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`retryCount` <- BigDecimalObject$fromJSON(jsonlite::toJSON(StreamStatusObject$retryCount, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`streamingWindowSize` <- BigDecimalObject$fromJSON(jsonlite::toJSON(StreamStatusObject$streamingWindowSize, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`totalInferences` <- BigDecimalObject$fromJSON(jsonlite::toJSON(StreamStatusObject$totalInferences, auto_unbox = TRUE))
    }
  )
)
