# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' StreamStatus Class
#'
#' @field state 
#' @field message 
#' @field progress 
#' @field clusterCount 
#' @field retryCount 
#' @field streamingWindowSize 
#' @field totalInferences 
#' @field lastModified 
#' @field lastModifiedDelta 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StreamStatus <- R6::R6Class(
  'StreamStatus',
  public = list(
    `state` = NULL,
    `message` = NULL,
    `progress` = NULL,
    `clusterCount` = NULL,
    `retryCount` = NULL,
    `streamingWindowSize` = NULL,
    `totalInferences` = NULL,
    `lastModified` = NULL,
    `lastModifiedDelta` = NULL,
    initialize = function(`state`, `message`, `progress`, `clusterCount`, `retryCount`, `streamingWindowSize`, `totalInferences`, `lastModified`, `lastModifiedDelta`){
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`progress`)) {
        stopifnot(is.numeric(`progress`), length(`progress`) == 1)
        stopifnot(R6::is.R6(`progress`))
        self$`progress` <- `progress`
      }
      if (!missing(`clusterCount`)) {
        stopifnot(is.numeric(`clusterCount`), length(`clusterCount`) == 1)
        stopifnot(R6::is.R6(`clusterCount`))
        self$`clusterCount` <- `clusterCount`
      }
      if (!missing(`retryCount`)) {
        stopifnot(is.numeric(`retryCount`), length(`retryCount`) == 1)
        stopifnot(R6::is.R6(`retryCount`))
        self$`retryCount` <- `retryCount`
      }
      if (!missing(`streamingWindowSize`)) {
        stopifnot(is.numeric(`streamingWindowSize`), length(`streamingWindowSize`) == 1)
        stopifnot(R6::is.R6(`streamingWindowSize`))
        self$`streamingWindowSize` <- `streamingWindowSize`
      }
      if (!missing(`totalInferences`)) {
        stopifnot(is.numeric(`totalInferences`), length(`totalInferences`) == 1)
        stopifnot(R6::is.R6(`totalInferences`))
        self$`totalInferences` <- `totalInferences`
      }
      if (!missing(`lastModified`)) {
        stopifnot(is.numeric(`lastModified`), length(`lastModified`) == 1)
        stopifnot(R6::is.R6(`lastModified`))
        self$`lastModified` <- `lastModified`
      }
      if (!missing(`lastModifiedDelta`)) {
        stopifnot(is.numeric(`lastModifiedDelta`), length(`lastModifiedDelta`) == 1)
        stopifnot(R6::is.R6(`lastModifiedDelta`))
        self$`lastModifiedDelta` <- `lastModifiedDelta`
      }
    },
    toJSON = function() {
      StreamStatusObject <- list()
      if (!is.null(self$`state`)) {
        StreamStatusObject[['state']] <- self$`state`
      }
      if (!is.null(self$`message`)) {
        StreamStatusObject[['message']] <- self$`message`
      }
      if (!is.null(self$`progress`)) {
        StreamStatusObject[['progress']] <- self$`progress`
      }
      if (!is.null(self$`clusterCount`)) {
        StreamStatusObject[['clusterCount']] <- self$`clusterCount`
      }
      if (!is.null(self$`retryCount`)) {
        StreamStatusObject[['retryCount']] <- self$`retryCount`
      }
      if (!is.null(self$`streamingWindowSize`)) {
        StreamStatusObject[['streamingWindowSize']] <- self$`streamingWindowSize`
      }
      if (!is.null(self$`totalInferences`)) {
        StreamStatusObject[['totalInferences']] <- self$`totalInferences`
      }
      if (!is.null(self$`lastModified`)) {
        StreamStatusObject[['lastModified']] <- self$`lastModified`
      }
      if (!is.null(self$`lastModifiedDelta`)) {
        StreamStatusObject[['lastModifiedDelta']] <- self$`lastModifiedDelta`
      }

      StreamStatusObject
    },
    fromJSON = function(StreamStatusJson) {
      StreamStatusObject <- jsonlite::fromJSON(StreamStatusJson, simplifyVector = FALSE)
      if (!is.null(StreamStatusObject$`state`)) {
        self$`state` <- StreamStatusObject$`state`
      }
      if (!is.null(StreamStatusObject$`message`)) {
        self$`message` <- StreamStatusObject$`message`
      }
      if (!is.null(StreamStatusObject$`progress`)) {
        self$`progress` <- StreamStatusObject$progress
      }
      if (!is.null(StreamStatusObject$`clusterCount`)) {
        self$`clusterCount` <- StreamStatusObject$clusterCount
      }
      if (!is.null(StreamStatusObject$`retryCount`)) {
        self$`retryCount` <- StreamStatusObject$retryCount
      }
      if (!is.null(StreamStatusObject$`streamingWindowSize`)) {
        self$`streamingWindowSize` <- StreamStatusObject$streamingWindowSize
      }
      if (!is.null(StreamStatusObject$`totalInferences`)) {
        self$`totalInferences` <- StreamStatusObject$totalInferences
      }
      if (!is.null(StreamStatusObject$`lastModified`)) {
        self$`lastModified` <- StreamStatusObject$lastModified
      }
      if (!is.null(StreamStatusObject$`lastModifiedDelta`)) {
        self$`lastModifiedDelta` <- StreamStatusObject$lastModifiedDelta
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "state": %s,
           "message": %s,
           "progress": %s,
           "clusterCount": %s,
           "retryCount": %s,
           "streamingWindowSize": %s,
           "totalInferences": %s,
           "lastModified": %s,
           "lastModifiedDelta": %s
        }',
        self$`state`,
        self$`message`,
        self$`progress`,
        self$`clusterCount`,
        self$`retryCount`,
        self$`streamingWindowSize`,
        self$`totalInferences`,
        self$`lastModified`,
        self$`lastModifiedDelta`
      )
    },
    fromJSONString = function(StreamStatusJson) {
      StreamStatusObject <- jsonlite::fromJSON(StreamStatusJson, simplifyVector = FALSE)
      self$`state` <- StreamStatusObject$`state`
      self$`message` <- StreamStatusObject$`message`
      self$`progress` <- StreamStatusObject$progress
      self$`clusterCount` <- StreamStatusObject$clusterCount
      self$`retryCount` <- StreamStatusObject$retryCount
      self$`streamingWindowSize` <- StreamStatusObject$streamingWindowSize
      self$`totalInferences` <- StreamStatusObject$totalInferences
      self$`lastModified` <- StreamStatusObject$lastModified
      self$`lastModifiedDelta` <- StreamStatusObject$lastModifiedDelta
    }
  )
)

