# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' StreamingEndpointUsageInfo Class
#'
#' @field callsTotal 
#' @field callsThisPeriod 
#' @field samplesTotal 
#' @field samplesThisPeriod 
#' @field lastCalled 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StreamingEndpointUsageInfo <- R6::R6Class(
  'StreamingEndpointUsageInfo',
  public = list(
    `callsTotal` = NULL,
    `callsThisPeriod` = NULL,
    `samplesTotal` = NULL,
    `samplesThisPeriod` = NULL,
    `lastCalled` = NULL,
    initialize = function(`callsTotal`, `callsThisPeriod`, `samplesTotal`, `samplesThisPeriod`, `lastCalled`){
      if (!missing(`callsTotal`)) {
        stopifnot(is.numeric(`callsTotal`), length(`callsTotal`) == 1)
        stopifnot(R6::is.R6(`callsTotal`))
        self$`callsTotal` <- `callsTotal`
      }
      if (!missing(`callsThisPeriod`)) {
        stopifnot(is.numeric(`callsThisPeriod`), length(`callsThisPeriod`) == 1)
        stopifnot(R6::is.R6(`callsThisPeriod`))
        self$`callsThisPeriod` <- `callsThisPeriod`
      }
      if (!missing(`samplesTotal`)) {
        stopifnot(is.numeric(`samplesTotal`), length(`samplesTotal`) == 1)
        stopifnot(R6::is.R6(`samplesTotal`))
        self$`samplesTotal` <- `samplesTotal`
      }
      if (!missing(`samplesThisPeriod`)) {
        stopifnot(is.numeric(`samplesThisPeriod`), length(`samplesThisPeriod`) == 1)
        stopifnot(R6::is.R6(`samplesThisPeriod`))
        self$`samplesThisPeriod` <- `samplesThisPeriod`
      }
      if (!missing(`lastCalled`)) {
        stopifnot(is.character(`lastCalled`), length(`lastCalled`) == 1)
        self$`lastCalled` <- `lastCalled`
      }
    },
    toJSON = function() {
      StreamingEndpointUsageInfoObject <- list()
      if (!is.null(self$`callsTotal`)) {
        StreamingEndpointUsageInfoObject[['callsTotal']] <- self$`callsTotal`
      }
      if (!is.null(self$`callsThisPeriod`)) {
        StreamingEndpointUsageInfoObject[['callsThisPeriod']] <- self$`callsThisPeriod`
      }
      if (!is.null(self$`samplesTotal`)) {
        StreamingEndpointUsageInfoObject[['samplesTotal']] <- self$`samplesTotal`
      }
      if (!is.null(self$`samplesThisPeriod`)) {
        StreamingEndpointUsageInfoObject[['samplesThisPeriod']] <- self$`samplesThisPeriod`
      }
      if (!is.null(self$`lastCalled`)) {
        StreamingEndpointUsageInfoObject[['lastCalled']] <- self$`lastCalled`
      }

      StreamingEndpointUsageInfoObject
    },
    fromJSON = function(StreamingEndpointUsageInfoJson) {
      StreamingEndpointUsageInfoObject <- jsonlite::fromJSON(StreamingEndpointUsageInfoJson, simplifyVector = FALSE)
      if (!is.null(StreamingEndpointUsageInfoObject$`callsTotal`)) {
        self$`callsTotal` <- StreamingEndpointUsageInfoObject$callsTotal
      }
      if (!is.null(StreamingEndpointUsageInfoObject$`callsThisPeriod`)) {
        self$`callsThisPeriod` <- StreamingEndpointUsageInfoObject$callsThisPeriod
      }
      if (!is.null(StreamingEndpointUsageInfoObject$`samplesTotal`)) {
        self$`samplesTotal` <- StreamingEndpointUsageInfoObject$samplesTotal
      }
      if (!is.null(StreamingEndpointUsageInfoObject$`samplesThisPeriod`)) {
        self$`samplesThisPeriod` <- StreamingEndpointUsageInfoObject$samplesThisPeriod
      }
      if (!is.null(StreamingEndpointUsageInfoObject$`lastCalled`)) {
        self$`lastCalled` <- StreamingEndpointUsageInfoObject$`lastCalled`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "callsTotal": %s,
           "callsThisPeriod": %s,
           "samplesTotal": %s,
           "samplesThisPeriod": %s,
           "lastCalled": %s
        }',
        self$`callsTotal`,
        self$`callsThisPeriod`,
        self$`samplesTotal`,
        self$`samplesThisPeriod`,
        self$`lastCalled`
      )
    },
    fromJSONString = function(StreamingEndpointUsageInfoJson) {
      StreamingEndpointUsageInfoObject <- jsonlite::fromJSON(StreamingEndpointUsageInfoJson, simplifyVector = FALSE)
      self$`callsTotal` <- StreamingEndpointUsageInfoObject$callsTotal
      self$`callsThisPeriod` <- StreamingEndpointUsageInfoObject$callsThisPeriod
      self$`samplesTotal` <- StreamingEndpointUsageInfoObject$samplesTotal
      self$`samplesThisPeriod` <- StreamingEndpointUsageInfoObject$samplesThisPeriod
      self$`lastCalled` <- StreamingEndpointUsageInfoObject$`lastCalled`
    }
  )
)

