# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' StreamingParameters Class
#'
#' @field anomalyHistoryWindow 
#' @field learningRateNumerator 
#' @field learningRateDenominator 
#' @field learningMaxClusters 
#' @field learningMaxSamples 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StreamingParameters <- R6::R6Class(
  'StreamingParameters',
  public = list(
    `anomalyHistoryWindow` = NULL,
    `learningRateNumerator` = NULL,
    `learningRateDenominator` = NULL,
    `learningMaxClusters` = NULL,
    `learningMaxSamples` = NULL,
    initialize = function(`anomalyHistoryWindow`, `learningRateNumerator`, `learningRateDenominator`, `learningMaxClusters`, `learningMaxSamples`){
      if (!missing(`anomalyHistoryWindow`)) {
        stopifnot(is.numeric(`anomalyHistoryWindow`), length(`anomalyHistoryWindow`) == 1)
        stopifnot(R6::is.R6(`anomalyHistoryWindow`))
        self$`anomalyHistoryWindow` <- `anomalyHistoryWindow`
      }
      if (!missing(`learningRateNumerator`)) {
        stopifnot(is.numeric(`learningRateNumerator`), length(`learningRateNumerator`) == 1)
        stopifnot(R6::is.R6(`learningRateNumerator`))
        self$`learningRateNumerator` <- `learningRateNumerator`
      }
      if (!missing(`learningRateDenominator`)) {
        stopifnot(is.numeric(`learningRateDenominator`), length(`learningRateDenominator`) == 1)
        stopifnot(R6::is.R6(`learningRateDenominator`))
        self$`learningRateDenominator` <- `learningRateDenominator`
      }
      if (!missing(`learningMaxClusters`)) {
        stopifnot(is.numeric(`learningMaxClusters`), length(`learningMaxClusters`) == 1)
        stopifnot(R6::is.R6(`learningMaxClusters`))
        self$`learningMaxClusters` <- `learningMaxClusters`
      }
      if (!missing(`learningMaxSamples`)) {
        stopifnot(is.numeric(`learningMaxSamples`), length(`learningMaxSamples`) == 1)
        stopifnot(R6::is.R6(`learningMaxSamples`))
        self$`learningMaxSamples` <- `learningMaxSamples`
      }
    },
    toJSON = function() {
      StreamingParametersObject <- list()
      if (!is.null(self$`anomalyHistoryWindow`)) {
        StreamingParametersObject[['anomalyHistoryWindow']] <- self$`anomalyHistoryWindow`
      }
      if (!is.null(self$`learningRateNumerator`)) {
        StreamingParametersObject[['learningRateNumerator']] <- self$`learningRateNumerator`
      }
      if (!is.null(self$`learningRateDenominator`)) {
        StreamingParametersObject[['learningRateDenominator']] <- self$`learningRateDenominator`
      }
      if (!is.null(self$`learningMaxClusters`)) {
        StreamingParametersObject[['learningMaxClusters']] <- self$`learningMaxClusters`
      }
      if (!is.null(self$`learningMaxSamples`)) {
        StreamingParametersObject[['learningMaxSamples']] <- self$`learningMaxSamples`
      }

      StreamingParametersObject
    },
    fromJSON = function(StreamingParametersJson) {
      StreamingParametersObject <- jsonlite::fromJSON(StreamingParametersJson, simplifyVector = FALSE)
      if (!is.null(StreamingParametersObject$`anomalyHistoryWindow`)) {
        self$`anomalyHistoryWindow` <- StreamingParametersObject$anomalyHistoryWindow
      }
      if (!is.null(StreamingParametersObject$`learningRateNumerator`)) {
        self$`learningRateNumerator` <- StreamingParametersObject$learningRateNumerator
      }
      if (!is.null(StreamingParametersObject$`learningRateDenominator`)) {
        self$`learningRateDenominator` <- StreamingParametersObject$learningRateDenominator
      }
      if (!is.null(StreamingParametersObject$`learningMaxClusters`)) {
        self$`learningMaxClusters` <- StreamingParametersObject$learningMaxClusters
      }
      if (!is.null(StreamingParametersObject$`learningMaxSamples`)) {
        self$`learningMaxSamples` <- StreamingParametersObject$learningMaxSamples
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "anomalyHistoryWindow": %s,
           "learningRateNumerator": %s,
           "learningRateDenominator": %s,
           "learningMaxClusters": %s,
           "learningMaxSamples": %s
        }',
        self$`anomalyHistoryWindow`,
        self$`learningRateNumerator`,
        self$`learningRateDenominator`,
        self$`learningMaxClusters`,
        self$`learningMaxSamples`
      )
    },
    fromJSONString = function(StreamingParametersJson) {
      StreamingParametersObject <- jsonlite::fromJSON(StreamingParametersJson, simplifyVector = FALSE)
      self$`anomalyHistoryWindow` <- StreamingParametersObject$anomalyHistoryWindow
      self$`learningRateNumerator` <- StreamingParametersObject$learningRateNumerator
      self$`learningRateDenominator` <- StreamingParametersObject$learningRateDenominator
      self$`learningMaxClusters` <- StreamingParametersObject$learningMaxClusters
      self$`learningMaxSamples` <- StreamingParametersObject$learningMaxSamples
    }
  )
)

