# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' StreamingEndpointUsageInfo Class
#'
#' @field callsTotal 
#' @field callsThisPeriod 
#' @field samplesTotal 
#' @field samplesThisPeriod 
#' @field lastCalled 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StreamingEndpointUsageInfo <- R6::R6Class(
  'StreamingEndpointUsageInfo',
  public = list(
    `callsTotal` = NULL,
    `callsThisPeriod` = NULL,
    `samplesTotal` = NULL,
    `samplesThisPeriod` = NULL,
    `lastCalled` = NULL,
    initialize = function(`callsTotal`, `callsThisPeriod`, `samplesTotal`, `samplesThisPeriod`, `lastCalled`){
      if (!missing(`callsTotal`)) {
        stopifnot(is.numeric(`callsTotal`), length(`callsTotal`) == 1)
        stopifnot(R6::is.R6(`callsTotal`))
        self$`callsTotal` <- `callsTotal`
      }
      if (!missing(`callsThisPeriod`)) {
        stopifnot(is.numeric(`callsThisPeriod`), length(`callsThisPeriod`) == 1)
        stopifnot(R6::is.R6(`callsThisPeriod`))
        self$`callsThisPeriod` <- `callsThisPeriod`
      }
      if (!missing(`samplesTotal`)) {
        stopifnot(is.numeric(`samplesTotal`), length(`samplesTotal`) == 1)
        stopifnot(R6::is.R6(`samplesTotal`))
        self$`samplesTotal` <- `samplesTotal`
      }
      if (!missing(`samplesThisPeriod`)) {
        stopifnot(is.numeric(`samplesThisPeriod`), length(`samplesThisPeriod`) == 1)
        stopifnot(R6::is.R6(`samplesThisPeriod`))
        self$`samplesThisPeriod` <- `samplesThisPeriod`
      }
      if (!missing(`lastCalled`)) {
        stopifnot(is.character(`lastCalled`), length(`lastCalled`) == 1)
        self$`lastCalled` <- `lastCalled`
      }
    },
    toJSON = function() {
      StreamingEndpointUsageInfoObject <- list()
      if (!is.null(self$`callsTotal`)) {
        StreamingEndpointUsageInfoObject[['callsTotal']] <- self$`callsTotal`$toJSON()
      }
      if (!is.null(self$`callsThisPeriod`)) {
        StreamingEndpointUsageInfoObject[['callsThisPeriod']] <- self$`callsThisPeriod`$toJSON()
      }
      if (!is.null(self$`samplesTotal`)) {
        StreamingEndpointUsageInfoObject[['samplesTotal']] <- self$`samplesTotal`$toJSON()
      }
      if (!is.null(self$`samplesThisPeriod`)) {
        StreamingEndpointUsageInfoObject[['samplesThisPeriod']] <- self$`samplesThisPeriod`$toJSON()
      }
      if (!is.null(self$`lastCalled`)) {
        StreamingEndpointUsageInfoObject[['lastCalled']] <- self$`lastCalled`
      }

      StreamingEndpointUsageInfoObject
    },
    fromJSON = function(StreamingEndpointUsageInfoJson) {
      StreamingEndpointUsageInfoObject <- jsonlite::fromJSON(StreamingEndpointUsageInfoJson)
      if (!is.null(StreamingEndpointUsageInfoObject$`callsTotal`)) {
        callsTotalObject <- BigDecimal$new()
        callsTotalObject$fromJSON(jsonlite::toJSON(StreamingEndpointUsageInfoObject$callsTotal, auto_unbox = TRUE))
        self$`callsTotal` <- callsTotalObject
      }
      if (!is.null(StreamingEndpointUsageInfoObject$`callsThisPeriod`)) {
        callsThisPeriodObject <- BigDecimal$new()
        callsThisPeriodObject$fromJSON(jsonlite::toJSON(StreamingEndpointUsageInfoObject$callsThisPeriod, auto_unbox = TRUE))
        self$`callsThisPeriod` <- callsThisPeriodObject
      }
      if (!is.null(StreamingEndpointUsageInfoObject$`samplesTotal`)) {
        samplesTotalObject <- BigDecimal$new()
        samplesTotalObject$fromJSON(jsonlite::toJSON(StreamingEndpointUsageInfoObject$samplesTotal, auto_unbox = TRUE))
        self$`samplesTotal` <- samplesTotalObject
      }
      if (!is.null(StreamingEndpointUsageInfoObject$`samplesThisPeriod`)) {
        samplesThisPeriodObject <- BigDecimal$new()
        samplesThisPeriodObject$fromJSON(jsonlite::toJSON(StreamingEndpointUsageInfoObject$samplesThisPeriod, auto_unbox = TRUE))
        self$`samplesThisPeriod` <- samplesThisPeriodObject
      }
      if (!is.null(StreamingEndpointUsageInfoObject$`lastCalled`)) {
        self$`lastCalled` <- StreamingEndpointUsageInfoObject$`lastCalled`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "callsTotal": %s,
           "callsThisPeriod": %s,
           "samplesTotal": %s,
           "samplesThisPeriod": %s,
           "lastCalled": %s
        }',
        self$`callsTotal`$toJSON(),
        self$`callsThisPeriod`$toJSON(),
        self$`samplesTotal`$toJSON(),
        self$`samplesThisPeriod`$toJSON(),
        self$`lastCalled`
      )
    },
    fromJSONString = function(StreamingEndpointUsageInfoJson) {
      StreamingEndpointUsageInfoObject <- jsonlite::fromJSON(StreamingEndpointUsageInfoJson)
      BigDecimalObject <- BigDecimal$new()
      self$`callsTotal` <- BigDecimalObject$fromJSON(jsonlite::toJSON(StreamingEndpointUsageInfoObject$callsTotal, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`callsThisPeriod` <- BigDecimalObject$fromJSON(jsonlite::toJSON(StreamingEndpointUsageInfoObject$callsThisPeriod, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`samplesTotal` <- BigDecimalObject$fromJSON(jsonlite::toJSON(StreamingEndpointUsageInfoObject$samplesTotal, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`samplesThisPeriod` <- BigDecimalObject$fromJSON(jsonlite::toJSON(StreamingEndpointUsageInfoObject$samplesThisPeriod, auto_unbox = TRUE))
      self$`lastCalled` <- StreamingEndpointUsageInfoObject$`lastCalled`
    }
  )
)
