# Amber API Server
#
# Boon Logic Amber API Server
#
# OpenAPI spec version: 1.0.3
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Version Class
#'
#' @field release 
#' @field api-version 
#' @field builder 
#' @field expert-api 
#' @field expert-common 
#' @field nano-secure 
#' @field swagger-ui 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Version <- R6::R6Class(
  'Version',
  public = list(
    `release` = NULL,
    `api-version` = NULL,
    `builder` = NULL,
    `expert-api` = NULL,
    `expert-common` = NULL,
    `nano-secure` = NULL,
    `swagger-ui` = NULL,
    initialize = function(`release`, `api-version`, `builder`, `expert-api`, `expert-common`, `nano-secure`, `swagger-ui`){
      if (!missing(`release`)) {
        stopifnot(is.character(`release`), length(`release`) == 1)
        self$`release` <- `release`
      }
      if (!missing(`api-version`)) {
        stopifnot(is.character(`api-version`), length(`api-version`) == 1)
        self$`api-version` <- `api-version`
      }
      if (!missing(`builder`)) {
        stopifnot(is.character(`builder`), length(`builder`) == 1)
        self$`builder` <- `builder`
      }
      if (!missing(`expert-api`)) {
        stopifnot(is.character(`expert-api`), length(`expert-api`) == 1)
        self$`expert-api` <- `expert-api`
      }
      if (!missing(`expert-common`)) {
        stopifnot(is.character(`expert-common`), length(`expert-common`) == 1)
        self$`expert-common` <- `expert-common`
      }
      if (!missing(`nano-secure`)) {
        stopifnot(is.character(`nano-secure`), length(`nano-secure`) == 1)
        self$`nano-secure` <- `nano-secure`
      }
      if (!missing(`swagger-ui`)) {
        stopifnot(is.character(`swagger-ui`), length(`swagger-ui`) == 1)
        self$`swagger-ui` <- `swagger-ui`
      }
    },
    toJSON = function() {
      VersionObject <- list()
      if (!is.null(self$`release`)) {
        VersionObject[['release']] <- self$`release`
      }
      if (!is.null(self$`api-version`)) {
        VersionObject[['api-version']] <- self$`api-version`
      }
      if (!is.null(self$`builder`)) {
        VersionObject[['builder']] <- self$`builder`
      }
      if (!is.null(self$`expert-api`)) {
        VersionObject[['expert-api']] <- self$`expert-api`
      }
      if (!is.null(self$`expert-common`)) {
        VersionObject[['expert-common']] <- self$`expert-common`
      }
      if (!is.null(self$`nano-secure`)) {
        VersionObject[['nano-secure']] <- self$`nano-secure`
      }
      if (!is.null(self$`swagger-ui`)) {
        VersionObject[['swagger-ui']] <- self$`swagger-ui`
      }

      VersionObject
    },
    fromJSON = function(VersionJson) {
      VersionObject <- jsonlite::fromJSON(VersionJson, simplifyVector = FALSE)
      if (!is.null(VersionObject$`release`)) {
        self$`release` <- VersionObject$`release`
      }
      if (!is.null(VersionObject$`api-version`)) {
        self$`api-version` <- VersionObject$`api-version`
      }
      if (!is.null(VersionObject$`builder`)) {
        self$`builder` <- VersionObject$`builder`
      }
      if (!is.null(VersionObject$`expert-api`)) {
        self$`expert-api` <- VersionObject$`expert-api`
      }
      if (!is.null(VersionObject$`expert-common`)) {
        self$`expert-common` <- VersionObject$`expert-common`
      }
      if (!is.null(VersionObject$`nano-secure`)) {
        self$`nano-secure` <- VersionObject$`nano-secure`
      }
      if (!is.null(VersionObject$`swagger-ui`)) {
        self$`swagger-ui` <- VersionObject$`swagger-ui`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "release": %s,
           "api-version": %s,
           "builder": %s,
           "expert-api": %s,
           "expert-common": %s,
           "nano-secure": %s,
           "swagger-ui": %s
        }',
        self$`release`,
        self$`api-version`,
        self$`builder`,
        self$`expert-api`,
        self$`expert-common`,
        self$`nano-secure`,
        self$`swagger-ui`
      )
    },
    fromJSONString = function(VersionJson) {
      VersionObject <- jsonlite::fromJSON(VersionJson, simplifyVector = FALSE)
      self$`release` <- VersionObject$`release`
      self$`api-version` <- VersionObject$`api-version`
      self$`builder` <- VersionObject$`builder`
      self$`expert-api` <- VersionObject$`expert-api`
      self$`expert-common` <- VersionObject$`expert-common`
      self$`nano-secure` <- VersionObject$`nano-secure`
      self$`swagger-ui` <- VersionObject$`swagger-ui`
    }
  )
)

